import {rowsFromTable,codeOf} from "../shared/grist-common.js";
import {readWorkbook,writeWorkbook} from "./xlsx-lite.js";
import {analyzeSheets} from "./import-core.js";
const $=s=>document.querySelector(s),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const TABLES=["CAMPAGNES","QUESTIONNAIRES","VERSIONS_QUESTIONNAIRES","QUESTIONS","TYPES_FICHES","DESTINATAIRES_CAMPAGNE","SOURCES_IMPORT","LIGNES_IMPORTEES","MAPPINGS_IMPORT","VALEURS_IMPORTEES"];
const S={data:{},analysis:null,workbook:null};
const unique=p=>`${p}_${Date.now().toString(36).toUpperCase()}_${Math.random().toString(36).slice(2,8).toUpperCase()}`;
async function fetchRows(t){return rowsFromTable(await grist.docApi.fetchTable(t))}
async function load(){try{const pairs=await Promise.all(TABLES.map(async t=>[t,await fetchRows(t)]));S.data=Object.fromEntries(pairs);renderCampaigns();status("")}catch(e){status(`Chargement impossible : ${e?.message||e}`,true)}}
function status(m,bad=false){$("#status").innerHTML=m?`<div class="${bad?"errorbox":"okbox"}">${esc(m)}</div>`:""}
function campaignGroup(c){return String(c?.Groupe_Campagne_Code||c?.Campagne_Code||"")}
function groupRows(c){const g=campaignGroup(c);return (S.data.CAMPAGNES||[]).filter(x=>campaignGroup(x)===g)}
function campaignLabel(c){return `${c.Nom||c.Campagne_Code} · ${String(c.Mode_diffusion||c.Mode_diffusion2||"").toUpperCase()||"mode non indiqué"}`}
function renderCampaigns(){const sel=$("#campaign"),rows=[...(S.data.CAMPAGNES||[])].filter(c=>c.Actif!==false&&String(c.Statut||c.Etat||"").toLowerCase()!=="supprimée"),seen=new Set(),opts=[];for(const c of rows){const g=campaignGroup(c);if(seen.has(g))continue;seen.add(g);opts.push(c)}sel.innerHTML='<option value="">— Sélectionner —</option>'+opts.map(c=>`<option value="${c.id}">${esc(campaignLabel(c))}</option>`).join("");sel.onchange=()=>{S.analysis=null;renderIdentifierTargets();$("#preview").innerHTML='<div class="empty">Aucun fichier analysé.</div>';$("#stage").disabled=true};renderIdentifierTargets()}
function selectedCampaign(){return (S.data.CAMPAGNES||[]).find(c=>String(c.id)===String($("#campaign").value))||null}
function renderIdentifierTargets(){const c=selectedCampaign(),target=$("#identifier-target"),help=$("#campaign-help");if(!c){target.innerHTML='<option value="">— Sélectionnez une campagne —</option>';help.textContent="";return}const mode=String(c.Mode_diffusion||c.Mode_diffusion2||"").toUpperCase(),opts=[];if(mode==="PERSONNALISE"){opts.push(["Valeur_personnalisation","Valeur de personnalisation"],["Valeur_personnalisation_Libelle","Libellé de personnalisation"],["Campagne_Code","Code technique du lien/campagne"]);help.textContent="Pour une campagne personnalisée, chaque ligne CAMPAGNES représente une valeur/participant du groupe."}else{const dest=(S.data.DESTINATAIRES_CAMPAGNE||[]).filter(d=>groupRows(c).some(x=>String(codeOf(d.Campagne_Code))===String(x.id)));if(dest.length){opts.push(["DEST:Identifiant_externe","Identifiant externe du destinataire"],["DEST:Email","E-mail du destinataire"],["DEST:Destinataire_Code","Code destinataire"]);help.textContent="Des destinataires explicites existent pour cette campagne ; ils peuvent être utilisés pour la correspondance."}else{opts.push(["Campagne_Code","Code de campagne"]);help.textContent="Attention : cette campagne ne possède pas de destinataires pré-identifiés. Un lien unique ne permet pas encore de rattacher un pré-remplissage à une personne avant son premier accès."}}target.innerHTML=opts.map(([v,l])=>`<option value="${esc(v)}">${esc(l)}</option>`).join("")}
function expectedIdentifiers(){const c=selectedCampaign(),target=$("#identifier-target").value;if(!c||!target)return[];if(target.startsWith("DEST:")){const f=target.slice(5),ids=new Set(groupRows(c).map(x=>String(x.id)));return (S.data.DESTINATAIRES_CAMPAGNE||[]).filter(d=>ids.has(String(codeOf(d.Campagne_Code)))).map(d=>String(d[f]??"").trim()).filter(Boolean)}return groupRows(c).map(x=>String(x[target]??"").trim()).filter(Boolean)}
function context(){const c=selectedCampaign();if(!c)throw new Error("Sélectionnez une campagne.");const versionId=String(codeOf(c.Version_Code)),questions=(S.data.QUESTIONS||[]).filter(q=>String(codeOf(q.Version_Code))===versionId),ficheTypes=(S.data.TYPES_FICHES||[]).filter(t=>String(codeOf(t.Version_Code))===versionId),identifierColumn=String($("#identifier-column").value||"").trim();if(!identifierColumn)throw new Error("Indiquez le nom de la colonne identifiant.");return{campaign:c,versionId,questions,ficheTypes,identifierColumn,expectedIdentifiers:expectedIdentifiers()}}
function previewHtml(a){const s=a.stats,err=a.errors,warn=a.warnings;return `<div class="stats"><div class="stat"><strong>${s.lines}</strong>Lignes détectées</div><div class="stat"><strong>${s.identifiers}</strong>Identifiants distincts</div><div class="stat"><strong>${s.participantsFound}</strong>Participants trouvés</div><div class="stat"><strong>${s.participantsNotFound}</strong>Non trouvés</div><div class="stat"><strong>${s.recognizedQuestions}</strong>Colonnes questions reconnues</div><div class="stat"><strong>${s.unknownColumns}</strong>Colonnes inconnues</div><div class="stat"><strong>${s.ficheCount}</strong>Fiches</div><div class="stat"><strong>${s.subCount}</strong>Sous-fiches</div></div>${err.length?`<div class="errorbox"><strong>${err.length} erreur(s) bloquante(s)</strong><ul class="list">${err.slice(0,40).map(x=>`<li>${esc(x)}</li>`).join("")}</ul>${err.length>40?`<div>… ${err.length-40} autre(s)</div>`:""}</div>`:'<div class="okbox">Aucune erreur bloquante détectée.</div>'}${warn.length?`<div class="warnbox"><strong>${warn.length} avertissement(s)</strong><ul class="list">${warn.slice(0,40).map(x=>`<li>${esc(x)}</li>`).join("")}</ul>${warn.length>40?`<div>… ${warn.length-40} autre(s)</div>`:""}</div>`:""}<div class="table-wrap"><table><thead><tr><th>Feuille</th><th>Ligne</th><th>Identifiant</th><th>Type</th><th>Code fiche</th><th>Parent</th><th>Lecture seule</th><th>Valeurs</th></tr></thead><tbody>${a.parsed.slice(0,200).map(r=>`<tr><td>${esc(r.sheet)}</td><td>${r.line}</td><td>${esc(r.identifier)}</td><td>${esc(r.kind==="REPONSES"?"Principal":r.typeCode)}</td><td>${esc(r.ficheCode)}</td><td>${esc(r.parentCode)}</td><td>${r.readOnlyElement?"Oui":"Non"}</td><td>${r.values.length}</td></tr>`).join("")}</tbody></table></div>`}
async function analyze(){try{const file=$("#file").files?.[0];if(!file)throw new Error("Choisissez un fichier Excel.");const ctx=context();S.workbook=await readWorkbook(file);S.analysis=analyzeSheets(S.workbook.sheets,ctx);S.analysis.ctx=ctx;S.analysis.fileName=file.name;$("#preview").innerHTML=previewHtml(S.analysis);$("#stage").disabled=!!S.analysis.errors.length;status(S.analysis.errors.length?"Le fichier contient des erreurs à corriger avant import.":"Analyse terminée. Les données peuvent être préparées.",!!S.analysis.errors.length)}catch(e){S.analysis=null;$("#stage").disabled=true;status(e?.message||e,true)}}
function typedFields(q,raw){const t=String(q?.Type_question||"").toLowerCase(),v=raw;if(t.includes("nombre")||t.includes("numérique")||t.includes("numerique")||t.includes("montant")){const n=Number(String(v).replace(",","."));return Number.isFinite(n)?{Valeur_nombre:n}:{Valeur_texte:String(v)}}if(t.includes("date"))return{Valeur_texte:String(v)};if(t.includes("bool")||t.includes("oui/non"))return{Valeur_booleen:["1","oui","true","vrai","yes","x"].includes(String(v).trim().toLowerCase())};if(q.Referentiel_Code)return{Valeur_reference:String(v)};return{Valeur_texte:String(v)}}
async function chunks(actions,size=150){for(let i=0;i<actions.length;i+=size)await grist.docApi.applyUserActions(actions.slice(i,i+size))}
async function stageImport(){if(!S.analysis||S.analysis.errors.length)return;try{$("#stage").disabled=true;const a=S.analysis,c=a.ctx.campaign,identifierTarget=$("#identifier-target").value,srcCode=unique("SRC_INIT"),description=`Pré-remplissage préparé depuis ${a.fileName}. Identifiant Excel: ${a.ctx.identifierColumn}; cible: ${$("#identifier-target").value}. Aucune réponse créée à cette étape.`;const result=await grist.docApi.applyUserActions([["AddRecord","SOURCES_IMPORT",null,{Source_Code:srcCode,Nom:`Pré-remplissage — ${c.Nom||c.Campagne_Code}`,Description:description,Campagne_Code:c.id,Actif:true}]]);S.data.SOURCES_IMPORT=await fetchRows("SOURCES_IMPORT");const src=(S.data.SOURCES_IMPORT||[]).find(x=>String(x.Source_Code)===srcCode);if(!src)throw new Error("La source d’import a été créée mais n’a pas pu être relue.");const headers=[...new Set(a.parsed.flatMap(r=>Object.keys(r.raw)))],qBy=new Map(a.ctx.questions.map(q=>[String(q.Question_Code).toUpperCase(),q]));const mapActions=[];headers.forEach((h,i)=>{let logic=h,type="META";const hu=h.toUpperCase();if(qBy.has(hu)){logic=String(qBy.get(hu).Question_Code);type="QUESTION"}else if(hu.endsWith("__LECTURE_SEULE")){logic=hu.slice(0,-"__LECTURE_SEULE".length);type="LECTURE_SEULE"}mapActions.push(["AddRecord","MAPPINGS_IMPORT",null,{Mapping_Code:unique("MAP"),Source_Code:src.id,Colonne_source:h,Champ_logique:logic,Libelle_affichage:h,Afficher:true,Ordre:i+1,Type_donnee:type}])});mapActions.push(["AddRecord","MAPPINGS_IMPORT",null,{Mapping_Code:unique("MAP"),Source_Code:src.id,Colonne_source:a.ctx.identifierColumn,Champ_logique:"__IDENTIFIANT__",Libelle_affichage:`Correspondance: ${identifierTarget}`,Afficher:false,Ordre:0,Type_donnee:"IDENTIFIANT"}]);await chunks(mapActions);
      for(const r of a.parsed){const lineCode=unique("LIG_INIT"),json=JSON.stringify({version:1,sourceFile:a.fileName,sheet:r.sheet,kind:r.kind,identifier:r.identifier,identifierColumn:a.ctx.identifierColumn,identifierTarget,typeFiche:r.typeCode||null,codeFiche:r.ficheCode||null,codeParent:r.parentCode||null,lectureSeuleElement:!!r.readOnlyElement,lectureSeuleQuestions:Object.fromEntries(r.values.filter(v=>v.readOnly).map(v=>[String(v.question.Question_Code),true])),raw:r.raw});await grist.docApi.applyUserActions([["AddRecord","LIGNES_IMPORTEES",null,{Ligne_Code:lineCode,Source_Code:src.id,Numero_ligne_source:r.line,Ligne_source_complete2:json}]]);const lineRows=await fetchRows("LIGNES_IMPORTEES"),line=lineRows.find(x=>String(x.Ligne_Code)===lineCode);if(!line)throw new Error(`Impossible de relire la ligne ${r.line}.`);const vals=r.values.map(v=>["AddRecord","VALEURS_IMPORTEES",null,{ValeurImportee_Code:unique("VIMP"),Ligne_Code:line.id,Champ_logique:String(v.question.Question_Code),...typedFields(v.question,v.raw)}]);if(vals.length)await chunks(vals)}
      status(`Import préparé enregistré (${a.parsed.length} ligne(s)). Aucune réponse n’a été créée ou modifiée.`);S.analysis=null;$("#preview").innerHTML='<div class="okbox">Données préparées enregistrées dans les tables d’import. Étape 1 terminée pour ce fichier.</div>'}catch(e){status(`Enregistrement impossible : ${e?.message||e}`,true);$("#stage").disabled=false}}
function downloadBlob(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000)}
function downloadModel(){const c=selectedCampaign();if(!c){status("Sélectionnez d’abord une campagne.",true);return}const versionId=String(codeOf(c.Version_Code)),qs=(S.data.QUESTIONS||[]).filter(q=>String(codeOf(q.Version_Code))===versionId),types=(S.data.TYPES_FICHES||[]).filter(t=>String(codeOf(t.Version_Code))===versionId),principal=qs.filter(q=>!codeOf(q.TypeFiche_Code)&&!q.Est_ligne_matrice).map(q=>String(q.Question_Code)),firstType=types[0],ficheQs=firstType?qs.filter(q=>String(codeOf(q.TypeFiche_Code))===String(firstType.id)&&!q.Est_ligne_matrice).map(q=>String(q.Question_Code)):[];const id=String($("#identifier-column").value||"IDENTIFIANT").trim()||"IDENTIFIANT",sheets=[{name:"REPONSES",rows:[[id,...principal.flatMap(q=>[q,`${q}__LECTURE_SEULE`])],["EXEMPLE_001",...principal.flatMap(()=>["","Non"])]]},{name:"FICHES",rows:[[id,"TYPE_FICHE","CODE_FICHE","LECTURE_SEULE_FICHE",...ficheQs.flatMap(q=>[q,`${q}__LECTURE_SEULE`])],["EXEMPLE_001",firstType?.TypeFiche_Code||"TYPE_FICHE","F001","Non",...ficheQs.flatMap(()=>["","Non"])]]},{name:"SOUS_FICHES",rows:[[id,"TYPE_FICHE","CODE_FICHE","CODE_PARENT","LECTURE_SEULE_FICHE"],["EXEMPLE_001","TYPE_SOUS_FICHE","SF001","F001","Non"]]}];downloadBlob(writeWorkbook(sheets),"modele_preremplissage_gristionnaire.xlsx")}
$("#refresh").onclick=load;$("#analyze").onclick=analyze;$("#stage").onclick=stageImport;$("#download-model").onclick=downloadModel;$("#identifier-column").onchange=()=>{S.analysis=null;$("#stage").disabled=true};$("#identifier-target").onchange=()=>{S.analysis=null;$("#stage").disabled=true};
grist.ready({requiredAccess:"full"});load();
