function u16(v,o){return v.getUint16(o,true)} function u32(v,o){return v.getUint32(o,true)}
async function inflateRaw(bytes){const ds=new DecompressionStream('deflate-raw');return new Uint8Array(await new Response(new Blob([bytes]).stream().pipeThrough(ds)).arrayBuffer())}
async function unzip(buf){const v=new DataView(buf);let e=-1;for(let i=v.byteLength-22;i>=Math.max(0,v.byteLength-65557);i--){if(u32(v,i)===0x06054b50){e=i;break}}if(e<0)throw new Error('Fichier XLSX invalide (archive ZIP introuvable).');const count=u16(v,e+10),cd=u32(v,e+16);let p=cd;const out=new Map();for(let n=0;n<count;n++){if(u32(v,p)!==0x02014b50)throw new Error('XLSX invalide (répertoire ZIP).');const method=u16(v,p+10),cs=u32(v,p+20),fn=u16(v,p+28),ex=u16(v,p+30),co=u16(v,p+32),lo=u32(v,p+42);const name=new TextDecoder().decode(new Uint8Array(buf,p+46,fn));const lfn=u16(v,lo+26),lex=u16(v,lo+28),start=lo+30+lfn+lex;let bytes=new Uint8Array(buf,start,cs);if(method===8)bytes=await inflateRaw(bytes);else if(method!==0)throw new Error('Compression XLSX non prise en charge.');out.set(name,bytes);p+=46+fn+ex+co}return out}
const xml=b=>new DOMParser().parseFromString(new TextDecoder().decode(b),'application/xml');
function colIndex(ref){let n=0;for(const c of String(ref).match(/[A-Z]+/i)?.[0]||'')n=n*26+c.toUpperCase().charCodeAt(0)-64;return n-1}
export async function readWorkbook(file){if(/\.csv$/i.test(file.name)){const text=await file.text(),lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());const sep=(lines[0]?.match(/;/g)||[]).length>(lines[0]?.match(/,/g)||[]).length?';':',';const parse=l=>{const a=[];let s='',q=false;for(let i=0;i<=l.length;i++){const c=l[i];if(c==='"'){if(q&&l[i+1]==='"'){s+='"';i++}else q=!q}else if((c===sep||i===l.length)&&!q){a.push(s);s=''}else s+=c??''}return a};return {sheets:[{name:'Données',rows:lines.map(parse)}]}}
 const z=await unzip(await file.arrayBuffer()),wb=xml(z.get('xl/workbook.xml')),rels=xml(z.get('xl/_rels/workbook.xml.rels'));const relMap=new Map([...rels.querySelectorAll('Relationship')].map(r=>[r.getAttribute('Id'),r.getAttribute('Target')]));let ss=[];if(z.has('xl/sharedStrings.xml'))ss=[...xml(z.get('xl/sharedStrings.xml')).querySelectorAll('si')].map(si=>[...si.querySelectorAll('t')].map(t=>t.textContent||'').join(''));const sheets=[];for(const s of wb.querySelectorAll('sheet')){const rid=s.getAttribute('r:id')||s.getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','id'),target=relMap.get(rid);if(!target)continue;const path=target.startsWith('/')?target.slice(1):'xl/'+target.replace(/^\.\//,'');const b=z.get(path);if(!b)continue;const d=xml(b),rows=[];for(const r of d.querySelectorAll('sheetData > row')){const arr=[];for(const c of r.querySelectorAll('c')){const idx=colIndex(c.getAttribute('r')),t=c.getAttribute('t'),vv=c.querySelector('v')?.textContent??'',inline=c.querySelector('is t')?.textContent??'';let val=t==='s'?ss[Number(vv)]??'':t==='inlineStr'?inline:t==='b'?(vv==='1'):vv;arr[idx]=val}rows.push(arr)}sheets.push({name:s.getAttribute('name')||`Feuille ${sheets.length+1}`,rows})}if(!sheets.length)throw new Error('Aucune feuille lisible dans ce fichier.');return {sheets}}


function xesc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&apos;"}[c]))}
function crc32(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0}
function le16(n){return new Uint8Array([n&255,(n>>>8)&255])}
function le32(n){return new Uint8Array([n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255])}
function concatBytes(parts){const n=parts.reduce((a,b)=>a+b.length,0),out=new Uint8Array(n);let o=0;for(const b of parts){out.set(b,o);o+=b.length}return out}
function zipStore(files){const enc=new TextEncoder(),locals=[],centrals=[];let offset=0;for(const [name,content] of files){const nb=enc.encode(name),data=typeof content==="string"?enc.encode(content):content,crc=crc32(data);const local=concatBytes([le32(0x04034b50),le16(20),le16(0),le16(0),le16(0),le16(0),le32(crc),le32(data.length),le32(data.length),le16(nb.length),le16(0),nb,data]);locals.push(local);const central=concatBytes([le32(0x02014b50),le16(20),le16(20),le16(0),le16(0),le16(0),le16(0),le32(crc),le32(data.length),le32(data.length),le16(nb.length),le16(0),le16(0),le16(0),le16(0),le32(0),le32(offset),nb]);centrals.push(central);offset+=local.length}const cd=concatBytes(centrals),body=concatBytes(locals),end=concatBytes([le32(0x06054b50),le16(0),le16(0),le16(files.length),le16(files.length),le32(cd.length),le32(body.length),le16(0)]);return new Blob([body,cd,end],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"})}
function colName(n){let s="";for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s}
function excelSerial(d){return d.getTime()/86400000+25569}
function cellXml(v,r,c){if(v===null||v===undefined||v==="")return"";const ref=colName(c)+(r+1);if(v instanceof Date&&!isNaN(v)){return `<c r="${ref}" s="1"><v>${excelSerial(v)}</v></c>`}if(typeof v==="number"&&Number.isFinite(v))return `<c r="${ref}"><v>${v}</v></c>`;if(typeof v==="boolean")return `<c r="${ref}" t="b"><v>${v?1:0}</v></c>`;return `<c r="${ref}" t="inlineStr"><is><t xml:space="preserve">${xesc(v)}</t></is></c>`}
function sheetXml(rows){const safe=(rows||[]).map(r=>Array.isArray(r)?r:[r]);let max=0;safe.forEach(r=>max=Math.max(max,r.length));const dim=max&&safe.length?`A1:${colName(max-1)}${safe.length}`:"A1";return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><dimension ref="${dim}"/><sheetViews><sheetView workbookViewId="0"/></sheetViews><sheetFormatPr defaultRowHeight="15"/><sheetData>${safe.map((row,ri)=>`<row r="${ri+1}">${row.map((v,ci)=>cellXml(v,ri,ci)).join("")}</row>`).join("")}</sheetData><autoFilter ref="${max&&safe.length?`A1:${colName(max-1)}${safe.length}`:"A1"}"/></worksheet>`}
function cleanSheetName(name,used){let s=String(name||"Feuille").replace(/[\\\/?*\[\]:]/g," ").trim().slice(0,31)||"Feuille",base=s,i=2;while(used.has(s)){const suf=` ${i++}`;s=base.slice(0,31-suf.length)+suf}used.add(s);return s}
export function writeWorkbook(sheets){const used=new Set(),ss=(sheets||[]).map(s=>({name:cleanSheetName(s.name,used),rows:s.rows||[]}));if(!ss.length)throw new Error("Aucune feuille à exporter.");const files=[];files.push(["[Content_Types].xml",`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>${ss.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join("")}</Types>`]);files.push(["_rels/.rels",`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`]);files.push(["xl/workbook.xml",`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${ss.map((s,i)=>`<sheet name="${xesc(s.name)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join("")}</sheets></workbook>`]);files.push(["xl/_rels/workbook.xml.rels",`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${ss.map((_,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join("")}<Relationship Id="rId${ss.length+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`]);files.push(["xl/styles.xml",`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><numFmts count="1"><numFmt numFmtId="164" formatCode="yyyy-mm-dd hh:mm"/></numFmts><fonts count="1"><font><sz val="11"/><name val="Calibri"/></font></fonts><fills count="1"><fill><patternFill patternType="none"/></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="164" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/></cellXfs></styleSheet>`]);ss.forEach((s,i)=>files.push([`xl/worksheets/sheet${i+1}.xml`,sheetXml(s.rows)]));return zipStore(files)}
