import {rowsFromTable,codeOf,isTrue} from "../shared/grist-common.js";
const $=s=>document.querySelector(s), esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const TABLES=["QUESTIONNAIRES","VERSIONS_QUESTIONNAIRE","VERSIONS_QUESTIONNAIRES","PAGES","SECTIONS","QUESTIONS","TYPES_FICHES","FILTRES_TYPES_FICHES","CHOIX_QUESTIONS","CONDITIONS","REGLES_CONDITION","FILTRES_CHOIX","COLONNES_MATRICE","DASHBOARDS","CAMPAGNES"];
const S={data:{},tab:"questionnaires",q:""};
function status(m,b=false){$("#status").innerHTML=m?`<div class="${b?"error":"success"}">${esc(m)}</div>`:""}
async function fetchOpt(t){try{return rowsFromTable(await grist.docApi.fetchTable(t))}catch{return null}}
async function load(){status("");for(const t of TABLES){const r=await fetchOpt(t);if(r)S.data[t]=r}if(!S.data.VERSIONS_QUESTIONNAIRES&&S.data.VERSIONS_QUESTIONNAIRE)S.data.VERSIONS_QUESTIONNAIRES=S.data.VERSIONS_QUESTIONNAIRE;render()}
const refs=(t)=>S.data[t]||[], refCode=(v,t,k)=>{const raw=codeOf(v);const row=refs(t).find(x=>String(x.id)===String(raw)||String(codeOf(x[k]))===String(raw));return row?codeOf(row[k]):raw};
const qCode=q=>codeOf(q.Questionnaire_Code), qName=q=>q.Titre||q.Nom||q.Description||qCode(q)||`Questionnaire ${q.id}`;
function versions(q){return refs("VERSIONS_QUESTIONNAIRES").filter(v=>refCode(v.Questionnaire_Code,"QUESTIONNAIRES","Questionnaire_Code")===qCode(q)).sort((a,b)=>Number(b.Numero_version||0)-Number(a.Numero_version||0)||Number(b.id)-Number(a.id))}
function belongs(row,v){return String(refCode(row.Version_Code,"VERSIONS_QUESTIONNAIRES","Version_Code"))===String(codeOf(v.Version_Code))}
function counts(v){return {pages:refs("PAGES").filter(x=>belongs(x,v)).length,sections:refs("SECTIONS").filter(x=>belongs(x,v)).length,questions:refs("QUESTIONS").filter(x=>belongs(x,v)&&!isTrue(x.Est_ligne_matrice)).length,fiches:refs("TYPES_FICHES").filter(x=>belongs(x,v)).length,conditions:refs("CONDITIONS").filter(x=>belongs(x,v)).length}}
function render(){document.querySelectorAll("[data-tab]").forEach(b=>b.classList.toggle("active",b.dataset.tab===S.tab));S.tab==="questionnaires"?renderQ():renderG()}
function renderQ(){const host=$("#content"),list=refs("QUESTIONNAIRES").filter(q=>!S.q||qName(q).toLowerCase().includes(S.q.toLowerCase())||qCode(q).toLowerCase().includes(S.q.toLowerCase()));host.innerHTML=`<div class="toolbar"><input id="search" placeholder="Rechercher un questionnaire…" value="${esc(S.q)}"><button id="only-models">Afficher les modèles</button></div><div class="grid">${list.map(q=>qCard(q)).join("")||'<div class="empty">Aucun questionnaire.</div>'}</div>`;$("#search").oninput=e=>{S.q=e.target.value;renderQ()};$("#only-models").onclick=()=>{S.q="__MODELS__";const cards=[...host.querySelectorAll(".card")];cards.forEach(c=>c.hidden=c.dataset.model!=="1")};host.querySelectorAll("[data-toggle-model]").forEach(b=>b.onclick=()=>toggleModel(b.dataset.toggleModel));host.querySelectorAll("[data-duplicate]").forEach(b=>b.onclick=()=>duplicateModel(b.dataset.duplicate))}
function qCard(q){const vs=versions(q),v=vs[0],c=v?counts(v):{pages:0,sections:0,questions:0,fiches:0,conditions:0},model=isTrue(q.Est_modele);return `<article class="card ${model?"model":""}" data-model="${model?1:0}"><h3>${esc(qName(q))}</h3><div class="meta">${esc(qCode(q))} · ${vs.length} version${vs.length>1?"s":""}</div><div class="badges"><span class="badge">${c.pages} pages</span><span class="badge">${c.sections} sections</span><span class="badge">${c.questions} questions</span><span class="badge">${c.fiches} fiches</span></div><div class="meta">${model?`Modèle · visibilité : ${esc(q.Visibilite_modele||"non précisée")}`:"Questionnaire standard"}</div><div class="actions"><button data-toggle-model="${q.id}">${model?"Retirer des modèles":"Ajouter aux modèles"}</button>${model&&v?`<button class="primary" data-duplicate="${q.id}">Créer depuis ce modèle</button>`:""}</div></article>`}
async function toggleModel(id){const q=refs("QUESTIONNAIRES").find(x=>String(x.id)===String(id));if(!q)return;try{await grist.docApi.applyUserActions([["UpdateRecord","QUESTIONNAIRES",Number(q.id),{Est_modele:!isTrue(q.Est_modele),Visibilite_modele:!isTrue(q.Est_modele)?(q.Visibilite_modele||"Interne"):q.Visibilite_modele}]]);await load();status(isTrue(q.Est_modele)?"Questionnaire retiré des modèles.":"Questionnaire ajouté aux modèles.")}catch(e){status(e.message||e,true)}}
function clean(row,skip=[]){const o={};for(const [k,v] of Object.entries(row)){if(k==="id"||k==="manualSort"||k.startsWith("gristHelper_")||skip.includes(k))continue;o[k]=v}return o}
function uid(prefix){return `${prefix}_${Date.now().toString(36).toUpperCase()}_${Math.random().toString(36).slice(2,7).toUpperCase()}`}
async function add(table,vals){await grist.docApi.applyUserActions([["AddRecord",table,null,vals]])}
async function duplicateModel(id){const q=refs("QUESTIONNAIRES").find(x=>String(x.id)===String(id)),v=versions(q)[0];if(!q||!v)return;const name=prompt("Nom du nouveau questionnaire :",`${qName(q)} - copie`);if(!name)return;if(!confirm(`Créer « ${name} » à partir du modèle « ${qName(q)} » ?\n\nLes campagnes et réponses ne seront pas copiées.`))return;status("Duplication du modèle en cours…");try{const newQC=uid("QUESTIONNAIRE"),newVC=uid("VERSION");const qv=clean(q,["Questionnaire_Code","Est_modele","Visibilite_modele","Titre"]);qv.Questionnaire_Code=newQC;qv.Titre=name;qv.Est_modele=false;qv.Visibilite_modele="";await add("QUESTIONNAIRES",qv);await load();const nq=refs("QUESTIONNAIRES").find(x=>qCode(x)===newQC);const vv=clean(v,["Version_Code","Questionnaire_Code","Numero_version","Titre"]);vv.Version_Code=newVC;vv.Questionnaire_Code=Number(nq.id);vv.Numero_version=1;vv.Titre=name;await add("VERSIONS_QUESTIONNAIRES",vv);await load();const nv=refs("VERSIONS_QUESTIONNAIRES").find(x=>codeOf(x.Version_Code)===newVC);await cloneDefinition(v,nv);await load();status(`Le questionnaire « ${name} » a été créé à partir du modèle.`)}catch(e){status(`Duplication impossible : ${e?.message||e}`,true)}}
async function cloneDefinition(ov,nv){const maps={cond:new Map(),page:new Map(),section:new Map(),fiche:new Map(),question:new Map(),choice:new Map()};const rows=t=>refs(t).filter(x=>belongs(x,ov));async function cloneLayer(table,list,map,codeField,transform=()=>({})){for(const old of list){const nc=uid(codeField.replace("_Code","").toUpperCase()),vals={...clean(old,[codeField,"Version_Code"]),...transform(old)};vals[codeField]=nc;if("Version_Code" in old)vals.Version_Code=Number(nv.id);await add(table,vals);const fresh=await fetchOpt(table),created=fresh.find(x=>codeOf(x[codeField])===nc);map.set(String(old.id),created.id);S.data[table]=fresh}}
await cloneLayer("CONDITIONS",rows("CONDITIONS"),maps.cond,"Condition_Code");
await cloneLayer("PAGES",rows("PAGES"),maps.page,"Page_Code",o=>({Condition_Code:null,Page_cible_Code:null}));
await cloneLayer("TYPES_FICHES",rows("TYPES_FICHES"),maps.fiche,"TypeFiche_Code",o=>({Parent_Code:null,Question_titre_Code:null}));
await cloneLayer("SECTIONS",rows("SECTIONS"),maps.section,"Section_Code",o=>({Page_Code:maps.page.get(String(codeOf(o.Page_Code)))||null,Condition_Code:null}));
await cloneLayer("QUESTIONS",rows("QUESTIONS"),maps.question,"Question_Code",o=>({Page_Code:maps.page.get(String(codeOf(o.Page_Code)))||null,Section_Code:maps.section.get(String(codeOf(o.Section_Code)))||null,TypeFiche_Code:maps.fiche.get(String(codeOf(o.TypeFiche_Code)))||null,Condition_obligation_Code:null,Condition_affichage_Code:null,Question_parente_Code:null}));
const actions=[];for(const old of rows("PAGES")){const ch={};if(codeOf(old.Condition_Code))ch.Condition_Code=maps.cond.get(String(codeOf(old.Condition_Code)))||null;if(codeOf(old.Page_cible_Code))ch.Page_cible_Code=maps.page.get(String(codeOf(old.Page_cible_Code)))||null;if(Object.keys(ch).length)actions.push(["UpdateRecord","PAGES",maps.page.get(String(old.id)),ch])}for(const old of rows("SECTIONS")){if(codeOf(old.Condition_Code))actions.push(["UpdateRecord","SECTIONS",maps.section.get(String(old.id)),{Condition_Code:maps.cond.get(String(codeOf(old.Condition_Code)))||null}])}for(const old of rows("TYPES_FICHES")){const ch={};if(codeOf(old.Parent_Code))ch.Parent_Code=maps.fiche.get(String(codeOf(old.Parent_Code)))||null;if(codeOf(old.Question_titre_Code))ch.Question_titre_Code=maps.question.get(String(codeOf(old.Question_titre_Code)))||null;if(Object.keys(ch).length)actions.push(["UpdateRecord","TYPES_FICHES",maps.fiche.get(String(old.id)),ch])}for(const old of rows("QUESTIONS")){const ch={};for(const [k,m] of [["Condition_obligation_Code",maps.cond],["Condition_affichage_Code",maps.cond],["Question_parente_Code",maps.question]])if(codeOf(old[k]))ch[k]=m.get(String(codeOf(old[k])))||null;if(Object.keys(ch).length)actions.push(["UpdateRecord","QUESTIONS",maps.question.get(String(old.id)),ch])}if(actions.length)await grist.docApi.applyUserActions(actions);
for(const old of refs("CHOIX_QUESTIONS").filter(x=>maps.question.has(String(codeOf(x.Question_Code))))){const vals=clean(old,["Choix_Code","Question_Code","Condition_Code"]);vals.Choix_Code=uid("CHOIX");vals.Question_Code=maps.question.get(String(codeOf(old.Question_Code)));vals.Condition_Code=maps.cond.get(String(codeOf(old.Condition_Code)))||null;await add("CHOIX_QUESTIONS",vals)}
for(const old of refs("REGLES_CONDITION").filter(x=>maps.cond.has(String(codeOf(x.Condition_Code))))){const vals=clean(old,["Regle_Code","Condition_Code","Question_source_Code","Question_comparaison_Code"]);vals.Regle_Code=uid("REGLE");vals.Condition_Code=maps.cond.get(String(codeOf(old.Condition_Code)));vals.Question_source_Code=maps.question.get(String(codeOf(old.Question_source_Code)))||null;vals.Question_comparaison_Code=maps.question.get(String(codeOf(old.Question_comparaison_Code)))||null;await add("REGLES_CONDITION",vals)}
for(const table of ["FILTRES_CHOIX","COLONNES_MATRICE"]){for(const old of refs(table).filter(x=>maps.question.has(String(codeOf(x.Question_Code))))){const codeField=table==="FILTRES_CHOIX"?"FiltreChoix_Code":"ColonneMatrice_Code",vals=clean(old,[codeField,"Question_Code","Question_source_Code"]);vals[codeField]=uid(table==="FILTRES_CHOIX"?"FILTRE":"COLMAT");vals.Question_Code=maps.question.get(String(codeOf(old.Question_Code)));if("Question_source_Code" in old)vals.Question_source_Code=maps.question.get(String(codeOf(old.Question_source_Code)))||null;await add(table,vals)}}
for(const old of refs("FILTRES_TYPES_FICHES").filter(x=>maps.fiche.has(String(codeOf(x.TypeFiche_Code))))){const vals=clean(old,["TypeFiche_Code","Question_Code"]);vals.TypeFiche_Code=maps.fiche.get(String(codeOf(old.TypeFiche_Code)));vals.Question_Code=maps.question.get(String(codeOf(old.Question_Code)))||null;await add("FILTRES_TYPES_FICHES",vals)} }
function dashboardConfig(r){try{return JSON.parse(r.Configuration_JSON||"{}")||{}}catch{return {}}}
function campaignName(code){const r=refs("CAMPAGNES").find(x=>String(x.Groupe_Campagne_Code||x.Campagne_Code)===String(code));return r?.Nom||code||"Campagne non identifiée"}
function renderG(){const all=[];for(const d of refs("DASHBOARDS")){const cfg=dashboardConfig(d);for(const g of Array.isArray(cfg.groupings)?cfg.groupings:[])all.push({d,g})}$("#content").innerHTML=`<div class="toolbar"><input id="gsearch" placeholder="Rechercher un regroupement…"></div><div class="grid" id="ggrid">${all.map(({d,g})=>`<article class="card" data-text="${esc(String(g.name||"").toLowerCase())}"><h3>${esc(g.name||"Regroupement sans nom")}</h3><div class="meta">Dashboard : ${esc(d.Nom||d.Dashboard_Code)}</div><div class="meta">Campagne : ${esc(campaignName(d.Campagne_Code))}</div><div class="badges"><span class="badge">${(g.groups||[]).length} groupes</span><span class="badge">Source : ${esc(g.source||"—")}</span></div><div class="details">${(g.groups||[]).map(x=>`<div class="group"><strong>${esc(x.label||"Groupe")}</strong><div class="muted">${(x.values||[]).map(esc).join(" · ")||"Aucune valeur"}</div></div>`).join("")}</div></article>`).join("")||'<div class="empty">Aucun regroupement trouvé dans les Dashboards.</div>'}</div>`;$("#gsearch").oninput=e=>{const q=e.target.value.toLowerCase();document.querySelectorAll("#ggrid .card").forEach(c=>c.hidden=q&&!c.dataset.text.includes(q))}}
document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{S.tab=b.dataset.tab;S.q="";render()});$("#refresh").onclick=load;grist.ready({requiredAccess:"full"});load();
