import test from 'node:test';import assert from 'node:assert/strict';import {analyzeSheets,sheetKind,boolVal,splitMultiValue} from '../preremplissage/import-core.js';
test('reconnait les feuilles attendues',()=>{assert.equal(sheetKind('Réponses'),'REPONSES');assert.equal(sheetKind('SOUS_FICHES'),'SOUS_FICHES');assert.equal(sheetKind('Divers'),'')});
test('booléens lecture seule',()=>{assert.equal(boolVal('Oui'),true);assert.equal(boolVal('non'),false)});
test('sépare les valeurs multiples',()=>{assert.deepEqual(splitMultiValue('A | B;C'),['A','B','C'])});
test('analyse questions, fiches et parent',()=>{const q=[{id:1,Question_Code:'VILLE',TypeFiche_Code:0},{id:2,Question_Code:'MONTANT',TypeFiche_Code:10}],t=[{id:10,TypeFiche_Code:'DEP',Version_Code:1}];const sheets=[{name:'REPONSES',rows:[['IDENTIFIANT','VILLE','VILLE__LECTURE_SEULE'],['A1','Paris','Oui']]},{name:'FICHES',rows:[['IDENTIFIANT','TYPE_FICHE','CODE_FICHE','MONTANT'],['A1','DEP','F1','25']]},{name:'SOUS_FICHES',rows:[['IDENTIFIANT','TYPE_FICHE','CODE_FICHE','CODE_PARENT'],['A1','DEP','SF1','F1']]}];const a=analyzeSheets(sheets,{questions:q,ficheTypes:t,identifierColumn:'IDENTIFIANT',expectedIdentifiers:['A1']});assert.deepEqual(a.errors,[]);assert.equal(a.stats.participantsFound,1);assert.equal(a.stats.ficheCount,1);assert.equal(a.stats.subCount,1);assert.equal(a.parsed[0].values[0].readOnly,true)});
test('bloque parent absent',()=>{const a=analyzeSheets([{name:'SOUS_FICHES',rows:[['IDENTIFIANT','TYPE_FICHE','CODE_FICHE','CODE_PARENT'],['A1','DEP','SF1','X']]}],{questions:[],ficheTypes:[{id:10,TypeFiche_Code:'DEP'}],identifierColumn:'IDENTIFIANT',expectedIdentifiers:[]});assert.ok(a.errors.some(x=>x.includes('parent')))});
test('bloque les doublons dans REPONSES',()=>{const a=analyzeSheets([{name:'REPONSES',rows:[['IDENTIFIANT','VILLE'],['A1','Paris'],['A1','Lyon']]}],{questions:[{id:1,Question_Code:'VILLE',TypeFiche_Code:0}],ficheTypes:[],identifierColumn:'IDENTIFIANT',expectedIdentifiers:['A1']});assert.ok(a.errors.some(x=>x.includes('présent plusieurs fois')))});

test('accepte un import contenant uniquement des fiches',()=>{const a=analyzeSheets([{name:'FICHES',rows:[['IDENTIFIANT','TYPE_FICHE','CODE_FICHE','MONTANT'],['A1','DEP','F1','25'],['A1','DEP','F2','40']]}],{questions:[{id:2,Question_Code:'MONTANT',TypeFiche_Code:10}],ficheTypes:[{id:10,TypeFiche_Code:'DEP',Version_Code:1}],identifierColumn:'IDENTIFIANT',expectedIdentifiers:['A1']});assert.deepEqual(a.errors,[]);assert.equal(a.stats.ficheCount,2);assert.equal(a.stats.identifiers,1);assert.equal(a.parsed.filter(x=>x.kind==='FICHES').length,2)});
