import {rowsFromTable,codeOf,isTrue} from "../shared/grist-common.js";
import {readWorkbook,writeWorkbook} from "./xlsx-lite.js";
const $=s=>document.querySelector(s), esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const S={refs:[],values:[],selected:null,preview:null};
function status(msg,bad=false){$("#status").innerHTML=msg?`<div class="${bad?"error":"success"}">${esc(msg)}</div>`:""}
async function fetchRows(t){return rowsFromTable(await grist.docApi.fetchTable(t))}
async function load(){try{const [refs,values]=await Promise.all([fetchRows("REFERENTIELS"),fetchRows("VALEURS_REFERENTIELS")]);S.refs=refs;S.values=values;if(S.selected&&!refs.some(r=>String(r.id)===String(S.selected)))S.selected=null;render()}catch(e){status(`Chargement impossible : ${e?.message||e}`,true)}}
const source=r=>String(r?.Type_source||"VALEURS_REFERENTIELS").trim().toUpperCase();
const refValues=r=>S.values.filter(v=>String(codeOf(v.Referentiel_Code))===String(r.id));
function render(){renderList();renderContent()}
function renderList(){const host=$("#refs"),rows=[...S.refs].sort((a,b)=>Number(a.manualSort||0)-Number(b.manualSort||0));host.innerHTML=rows.map(r=>`<button class="ref-card ${String(r.id)===String(S.selected)?"active":""}" data-id="${r.id}"><strong>${esc(r.Nom||r.Referentiel_Code)}</strong><span>${esc(r.Referentiel_Code)} · ${isTrue(r.Hierarchique)?"Hiérarchique":"Simple"}${source(r)!=="VALEURS_REFERENTIELS"?` · Source ${esc(source(r))}`:""}</span></button>`).join("")||'<div class="muted">Aucun référentiel.</div>';host.querySelectorAll(".ref-card").forEach(b=>b.onclick=()=>{S.selected=Number(b.dataset.id);S.preview=null;render()})}
function valueTree(rows){const byId=new Map(rows.map(r=>[String(r.id),r]));const depth=r=>{let d=0,p=codeOf(r.Parent_Code),seen=new Set();while(p&&byId.has(String(p))&&!seen.has(String(p))){seen.add(String(p));d++;p=codeOf(byId.get(String(p)).Parent_Code)}return d};return [...rows].sort((a,b)=>Number(a.Ordre||0)-Number(b.Ordre||0)||Number(a.id)-Number(b.id)).map(r=>({...r,_depth:depth(r),_parent:byId.get(String(codeOf(r.Parent_Code)))?.Code||""}))}
function renderContent(){const host=$("#content"),r=S.refs.find(x=>String(x.id)===String(S.selected));if(!r){host.className="empty-state";host.innerHTML="Sélectionnez un référentiel ou créez-en un.";return}host.className="";const vals=valueTree(refValues(r)),managed=source(r)==="VALEURS_REFERENTIELS";host.innerHTML=`<div class="head"><div><h2>${esc(r.Nom||r.Referentiel_Code)}</h2><div class="meta">${esc(r.Referentiel_Code)} · ${isTrue(r.Hierarchique)?"Hiérarchique":"Simple"} · ${vals.length} valeur${vals.length>1?"s":""}</div>${r.Description?`<p>${esc(r.Description)}</p>`:""}</div><div class="actions"><button class="btn" id="edit-ref">Modifier</button><button class="btn" id="download-model">Télécharger le modèle</button><button class="btn" id="export-ref">Exporter</button></div></div>${managed?importHtml(r):`<div class="preview bad">Ce référentiel utilise la source <strong>${esc(source(r))}</strong>. Ses valeurs ne sont pas gérées dans VALEURS_REFERENTIELS ; l’import est donc désactivé ici.</div>`}<h3>Valeurs actuelles</h3><div class="table-wrap"><table><thead><tr><th>Code</th><th>Libellé</th>${isTrue(r.Hierarchique)?"<th>Parent</th><th>Niveau</th>":""}<th>Ordre</th><th>Actif</th></tr></thead><tbody>${vals.map(v=>`<tr><td>${`<span class="indent" style="width:${v._depth*14}px"></span>`}${esc(v.Code)}</td><td>${esc(v.Libelle)}</td>${isTrue(r.Hierarchique)?`<td>${esc(v._parent)}</td><td>${esc(v.Niveau??v._depth)}</td>`:""}<td>${esc(v.Ordre)}</td><td>${isTrue(v.Actif)?"Oui":"Non"}</td></tr>`).join("")||'<tr><td colspan="6" class="muted">Aucune valeur.</td></tr>'}</tbody></table></div>`;$("#edit-ref").onclick=()=>openRef(r);$("#download-model").onclick=()=>downloadModel(r);$("#export-ref").onclick=()=>exportRef(r);if(managed)bindImport(r)}
function importHtml(r){return `<div class="import-box"><h3>Importer des valeurs</h3><div class="import-grid"><label class="file-field">Fichier Excel ou CSV<input id="import-file" type="file" accept=".xlsx,.csv"></label><label>Mode<select id="import-mode"><option value="update">Mettre à jour + ajouter</option><option value="add">Ajouter uniquement</option><option value="sync">Synchroniser avec le fichier</option></select></label><button id="analyze-import" class="btn">Analyser</button></div><div class="hint">Colonnes attendues : <strong>Code, Libelle, Ordre, Actif</strong>${isTrue(r.Hierarchique)?" et <strong>Parent_Code</strong>":""}. En mode Synchroniser, les codes absents du fichier seront supprimés après confirmation.</div><div id="import-preview">${S.preview?previewHtml(S.preview):""}</div></div>`}
function previewHtml(p){return `<div class="preview ${p.errors.length?"bad":"ok"}"><strong>${p.rows.length} ligne${p.rows.length>1?"s":""} détectée${p.rows.length>1?"s":""}</strong> · ${p.newCount} nouvelle${p.newCount>1?"s":""} · ${p.updateCount} existante${p.updateCount>1?"s":""}${p.removeCount?` · ${p.removeCount} absente${p.removeCount>1?"s":""} du fichier`:""}${p.errors.length?`<div class="danger">${p.errors.map(esc).join("<br>")}</div>`:`<div>Aucune anomalie détectée.</div><button id="run-import" class="btn btn-primary" style="margin-top:8px">Importer maintenant</button>`}</div>`}
function openRef(r=null){const f=$("#ref-form");f.reset();f.elements.id.value=r?.id||"";f.elements.name.value=r?.Nom||"";f.elements.code.value=r?.Referentiel_Code||"";f.elements.description.value=r?.Description||"";f.elements.hierarchical.value=isTrue(r?.Hierarchique)?"1":"0";f.elements.active.checked=r?isTrue(r.Actif):true;$("#ref-dialog-title").textContent=r?"Modifier le référentiel":"Nouveau référentiel";$("#ref-dialog").showModal()}
function normalizeCode(v){return String(v??"").trim()}
function boolVal(v,def=true){const s=String(v??"").trim().toLowerCase();if(v===""||v==null)return def;return !["0","non","false","faux","n"].includes(s)}
function downloadBlob(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000)}
function modelRows(r){const head=isTrue(r.Hierarchique)?["Code","Libelle","Parent_Code","Ordre","Actif"]:["Code","Libelle","Ordre","Actif"];const ex=isTrue(r.Hierarchique)?[["DIRECTION_A","Direction A","",1,"Oui"],["BUREAU_A1","Bureau A1","DIRECTION_A",2,"Oui"]]:[["A","Première valeur",1,"Oui"],["B","Deuxième valeur",2,"Oui"]];return [head,...ex]}
function downloadModel(r){downloadBlob(writeWorkbook([{name:"Valeurs",rows:modelRows(r)}]),`modele_referentiel_${r.Referentiel_Code}.xlsx`)}
function exportRef(r){const rows=valueTree(refValues(r)),head=isTrue(r.Hierarchique)?["Code","Libelle","Parent_Code","Ordre","Actif"]:["Code","Libelle","Ordre","Actif"],data=rows.map(v=>isTrue(r.Hierarchique)?[v.Code,v.Libelle,v._parent,v.Ordre,isTrue(v.Actif)?"Oui":"Non"]:[v.Code,v.Libelle,v.Ordre,isTrue(v.Actif)?"Oui":"Non"]);downloadBlob(writeWorkbook([{name:"Valeurs",rows:[head,...data]}]),`referentiel_${r.Referentiel_Code}.xlsx`)}
async function parseImport(file,r,mode){const wb=await readWorkbook(file),sheet=wb.sheets[0],rows=sheet?.rows||[];if(rows.length<2)throw new Error("Le fichier ne contient aucune donnée.");const headers=rows[0].map(x=>String(x??"").trim()),idx=n=>headers.findIndex(h=>h.toLowerCase()===n.toLowerCase()),need=["Code","Libelle"],errors=[];for(const n of need)if(idx(n)<0)errors.push(`Colonne obligatoire manquante : ${n}.`);if(isTrue(r.Hierarchique)&&idx("Parent_Code")<0)errors.push("Colonne obligatoire manquante : Parent_Code.");const data=rows.slice(1).filter(a=>a.some(x=>String(x??"").trim()!=="")).map((a,i)=>({line:i+2,Code:normalizeCode(a[idx("Code")]),Libelle:String(a[idx("Libelle")]??"").trim(),Parent_Code:idx("Parent_Code")>=0?normalizeCode(a[idx("Parent_Code")]):"",Ordre:idx("Ordre")>=0&&String(a[idx("Ordre")]??"").trim()!==""?Number(a[idx("Ordre")]):i+1,Actif:idx("Actif")>=0?boolVal(a[idx("Actif")],true):true}));const seen=new Set();for(const x of data){if(!x.Code)errors.push(`Ligne ${x.line} : Code vide.`);else if(seen.has(x.Code))errors.push(`Code en double dans le fichier : ${x.Code}.`);seen.add(x.Code);if(!x.Libelle)errors.push(`Ligne ${x.line} (${x.Code||"?"}) : Libelle vide.`);if(!Number.isFinite(x.Ordre))errors.push(`Ligne ${x.line} (${x.Code||"?"}) : Ordre invalide.`)}if(isTrue(r.Hierarchique)){for(const x of data)if(x.Parent_Code&&!seen.has(x.Parent_Code))errors.push(`Ligne ${x.line} (${x.Code}) : parent ${x.Parent_Code} absent du fichier.`);const by=new Map(data.map(x=>[x.Code,x]));for(const x of data){let p=x.Parent_Code,vis=new Set([x.Code]);while(p){if(vis.has(p)){errors.push(`Hiérarchie circulaire détectée autour de ${x.Code}.`);break}vis.add(p);p=by.get(p)?.Parent_Code||""}}}const current=refValues(r),byCode=new Map(current.map(v=>[normalizeCode(v.Code),v])),newCount=data.filter(x=>!byCode.has(x.Code)).length,updateCount=data.length-newCount,removeCount=mode==="sync"?current.filter(v=>!seen.has(normalizeCode(v.Code))).length:0;return{rows:data,errors:[...new Set(errors)],newCount,updateCount,removeCount,mode}}
function bindImport(r){$("#analyze-import").onclick=async()=>{const file=$("#import-file").files[0];if(!file){status("Choisissez d’abord un fichier.",true);return}try{S.preview=await parseImport(file,r,$("#import-mode").value);$("#import-preview").innerHTML=previewHtml(S.preview);const b=$("#run-import");if(b)b.onclick=()=>runImport(r,S.preview)}catch(e){status(`Analyse impossible : ${e?.message||e}`,true)}}}
function stableValueCode(r,code,used){const base=`VR_${String(r.Referentiel_Code||"REF").replace(/[^A-Za-z0-9]+/g,"_")}_${String(code).replace(/[^A-Za-z0-9]+/g,"_")}`.slice(0,90);let x=base,n=2;while(used.has(x))x=`${base}_${n++}`;used.add(x);return x}
function computeLevels(rows){const by=new Map(rows.map(x=>[x.Code,x])),memo=new Map();const lev=x=>{if(memo.has(x.Code))return memo.get(x.Code);const n=x.Parent_Code&&by.has(x.Parent_Code)?lev(by.get(x.Parent_Code))+1:0;memo.set(x.Code,n);return n};rows.forEach(lev);return memo}
async function runImport(r,p){if(p.errors.length)return;const msg=p.mode==="sync"?`Synchroniser ce référentiel ? ${p.removeCount} valeur(s) absente(s) du fichier seront supprimées.`:`Importer ${p.rows.length} valeur(s) ?`;if(!confirm(msg))return;try{const current=refValues(r),byCode=new Map(current.map(v=>[normalizeCode(v.Code),v])),used=new Set(S.values.map(v=>String(v.ValeurRef_Code||""))),levels=computeLevels(p.rows),actions=[];for(const x of p.rows){const old=byCode.get(x.Code);if(old){if(p.mode!=="add")actions.push(["UpdateRecord","VALEURS_REFERENTIELS",Number(old.id),{Code:x.Code,Libelle:x.Libelle,Ordre:x.Ordre,Actif:x.Actif,Niveau:levels.get(x.Code)||0}])}else actions.push(["AddRecord","VALEURS_REFERENTIELS",null,{ValeurRef_Code:stableValueCode(r,x.Code,used),Referentiel_Code:Number(r.id),Code:x.Code,Libelle:x.Libelle,Ordre:x.Ordre,Actif:x.Actif,Niveau:levels.get(x.Code)||0}])}if(p.mode==="sync"){const keep=new Set(p.rows.map(x=>x.Code));for(const old of current)if(!keep.has(normalizeCode(old.Code)))actions.push(["RemoveRecord","VALEURS_REFERENTIELS",Number(old.id)])}if(actions.length)await grist.docApi.applyUserActions(actions);await load();const fresh=S.refs.find(x=>String(x.id)===String(r.id)),freshVals=refValues(fresh),freshByCode=new Map(freshVals.map(v=>[normalizeCode(v.Code),v])),parentActions=[];for(const x of p.rows){const row=freshByCode.get(x.Code);if(!row)continue;const parent=x.Parent_Code?freshByCode.get(x.Parent_Code):null;parentActions.push(["UpdateRecord","VALEURS_REFERENTIELS",Number(row.id),{Parent_Code:parent?Number(parent.id):null,Niveau:levels.get(x.Code)||0}])}if(parentActions.length)await grist.docApi.applyUserActions(parentActions);S.preview=null;await load();status(`Import terminé : ${p.rows.length} ligne(s) traitée(s).`)}catch(e){status(`Import impossible : ${e?.message||e}`,true)}}
$("#new-ref").onclick=()=>openRef();$("#refresh").onclick=load;$("#close-ref").onclick=$("#cancel-ref").onclick=()=>$("#ref-dialog").close();
$("#ref-form").onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,fd=new FormData(f),id=fd.get("id"),code=normalizeCode(fd.get("code")),name=String(fd.get("name")||"").trim();if(!code||!name)return;const duplicate=S.refs.find(r=>String(r.Referentiel_Code)===code&&String(r.id)!==String(id));if(duplicate){status(`Le code ${code} existe déjà.`,true);return}const existing=id?S.refs.find(r=>String(r.id)===String(id)):null;const vals={Referentiel_Code:code,Nom:name,Description:String(fd.get("description")||"").trim(),Hierarchique:fd.get("hierarchical")==="1",Actif:fd.get("active")==="on",Type_source:existing?String(existing.Type_source||"VALEURS_REFERENTIELS"):"VALEURS_REFERENTIELS"};try{if(id)await grist.docApi.applyUserActions([["UpdateRecord","REFERENTIELS",Number(id),vals]]);else await grist.docApi.applyUserActions([["AddRecord","REFERENTIELS",null,vals]]);$("#ref-dialog").close();await load();if(!id){const nr=S.refs.find(r=>String(r.Referentiel_Code)===code);if(nr)S.selected=nr.id;render()}status(id?"Référentiel modifié.":"Référentiel créé.")}catch(err){status(`Enregistrement impossible : ${err?.message||err}`,true)}};
grist.ready({requiredAccess:"full"});load();
