import {rowsFromTable,codeOf,isTrue,sortByOrder} from "../shared/grist-common.js";
import {serializeAnswer,generateResumeToken} from "../questionnaire/persistence.js";
import {mulberry32,hashSeed,intBetween,fakeSimpleValue,generateAnswers,matrixKind,isMultiQuestion,resolveRow,optionPool,rootFicheTypes,childTypes,safeCountRange,conditionVisible} from "./core.js";
const $=s=>document.querySelector(s),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const TABLES=["CAMPAGNES","QUESTIONNAIRES","VERSIONS_QUESTIONNAIRES","QUESTIONS","TYPES_FICHES","CHOIX_QUESTIONS","CONDITIONS","REGLES_CONDITION","REFERENTIELS","VALEURS_REFERENTIELS","STRUCTURES","COLONNES_MATRICE","REPONSES","ELEMENTS_REPONSE","VALEURS_REPONSE","SELECTIONS_REPONSE"];
const S={data:{}};const unique=p=>`${p}_${Date.now().toString(36).toUpperCase()}_${Math.random().toString(36).slice(2,8).toUpperCase()}`;
async function fetchRows(t){return rowsFromTable(await grist.docApi.fetchTable(t))}
async function load(){try{const pairs=await Promise.all(TABLES.map(async t=>[t,await fetchRows(t)]));S.data=Object.fromEntries(pairs);renderCampaigns();updateSummary();status("")}catch(e){status(`Chargement impossible : ${e?.message||e}`,true)}}
function status(m,bad=false){$("#status").innerHTML=m?`<div class="${bad?"errorbox":"okbox"}">${esc(m)}</div>`:""}
function log(lines){$("#log").classList.remove("empty");$("#log").textContent=Array.isArray(lines)?lines.join("\n"):String(lines)}
function campaignGroup(c){return String(c?.Groupe_Campagne_Code||c?.Campagne_Code||"")}
function groupRows(c){const g=campaignGroup(c);return(S.data.CAMPAGNES||[]).filter(x=>campaignGroup(x)===g)}
function campaignLabel(c){return `${c.Nom||c.Campagne_Code} · ${String(c.Mode_diffusion||c.Mode_diffusion2||"").toUpperCase()||"mode non indiqué"}`}
function selectedCampaign(){return(S.data.CAMPAGNES||[]).find(c=>String(c.id)===String($("#campaign").value))||null}
function renderCampaigns(){const previous=$("#campaign").value,rows=[...(S.data.CAMPAGNES||[])].filter(c=>c.Actif!==false&&String(c.Statut||c.Etat||"").toLowerCase()!=="supprimée"),seen=new Set(),opts=[];for(const c of rows){const g=campaignGroup(c);if(seen.has(g))continue;seen.add(g);opts.push(c)}$("#campaign").innerHTML='<option value="">— Sélectionner —</option>'+opts.map(c=>`<option value="${c.id}">${esc(campaignLabel(c))}</option>`).join("");if(opts.some(c=>String(c.id)===String(previous)))$("#campaign").value=previous;$("#campaign").onchange=()=>updateSummary()}
function sameCampaignRef(r,c){const ids=new Set(groupRows(c).flatMap(x=>[String(x.id),String(codeOf(x.Campagne_Code))]));return ids.has(String(codeOf(r.Campagne_Code)))}
function testResponses(c){return c?(S.data.REPONSES||[]).filter(r=>!isTrue(r.Supprime_logiquement)&&isTrue(r.Est_test)&&sameCampaignRef(r,c)):[]}
function realResponses(c){return c?(S.data.REPONSES||[]).filter(r=>!isTrue(r.Supprime_logiquement)&&!isTrue(r.Est_test)&&sameCampaignRef(r,c)):[]}
function updateSummary(){const c=selectedCampaign(),info=$("#campaign-info"),summary=$("#summary"),del=$("#delete");if(!c){info.textContent="";summary.textContent="Sélectionnez une campagne.";del.disabled=true;return}const tr=testResponses(c),rr=realResponses(c),version=resolveRow(c.Version_Code,S.data.VERSIONS_QUESTIONNAIRES,"Version_Code"),q=(S.data.QUESTIONNAIRES||[]).find(x=>String(x.id)===String(codeOf(c.Questionnaire_Code)))||null;info.textContent=`Questionnaire : ${q?.Titre||q?.Nom||"—"} · Version : ${version?.Titre||version?.Numero_version||codeOf(c.Version_Code)||"—"} · ${rr.length} vraie(s) réponse(s)`;const elements=(S.data.ELEMENTS_REPONSE||[]).filter(e=>tr.some(r=>String(codeOf(e.Reponse_Code))===String(r.id)));const fiches=elements.filter(e=>String(e.Type_element||"").toLowerCase()==="fiche").length,subs=elements.filter(e=>String(e.Type_element||"").toLowerCase()==="sous-fiche").length;summary.innerHTML=`<span class="pill">${tr.length} réponse(s) simulée(s)</span><span class="pill">${fiches} fiche(s)</span><span class="pill">${subs} sous-fiche(s)</span><span class="pill">${rr.length} réponse(s) réelle(s)</span>`;del.disabled=!tr.length}
function versionContext(c){const version=resolveRow(c.Version_Code,S.data.VERSIONS_QUESTIONNAIRES,"Version_Code");if(!version)throw new Error("Version du questionnaire introuvable.");const vid=String(version.id),byVersion=(r)=>String(codeOf(r.Version_Code))===vid;return{version,questions:(S.data.QUESTIONS||[]).filter(byVersion),ficheTypes:(S.data.TYPES_FICHES||[]).filter(byVersion),choices:S.data.CHOIX_QUESTIONS||[],conditions:(S.data.CONDITIONS||[]).filter(byVersion),rules:S.data.REGLES_CONDITION||[],referentials:S.data.REFERENTIELS||[],referentialValues:S.data.VALEURS_REFERENTIELS||[],structures:S.data.STRUCTURES||[],matrixColumns:S.data.COLONNES_MATRICE||[]}}
function qForType(ctx,type){return sortByOrder(ctx.questions.filter(q=>q.Active!==false&&!isTrue(q.Est_ligne_matrice)&&String(codeOf(q.TypeFiche_Code))===String(type.id)))}
function principalQuestions(ctx){return sortByOrder(ctx.questions.filter(q=>q.Active!==false&&!isTrue(q.Est_ligne_matrice)&&!codeOf(q.TypeFiche_Code)))}
function matrixRows(q,ctx){const qc=codeOf(q.Question_Code);return sortByOrder(ctx.questions.filter(r=>r.Active!==false&&isTrue(r.Est_ligne_matrice)&&(()=>{const p=resolveRow(r.Question_parente_Code,ctx.questions,"Question_Code");return p&&String(p.id)===String(q.id)})()))}
function matrixCols(q,ctx){const kind=matrixKind(q);if(["radio","checkbox"].includes(kind))return sortByOrder(ctx.choices.filter(c=>c.Actif!==false&&(()=>{const p=resolveRow(c.Question_Code,[q],"Question_Code");return !!p})()));return sortByOrder(ctx.matrixColumns.filter(c=>c.Active!==false&&(()=>{const raw=codeOf(c.Question_Code);return raw===String(q.id)||raw===codeOf(q.Question_Code)})()))}
function gristFields(q,value,ctx){const fields=serializeAnswer(q,value,ctx);if(fields.Valeur_reference_Code){const row=resolveRow(fields.Valeur_reference_Code,ctx.referentialValues,"ValeurRef_Code");fields.Valeur_reference_Code=row?.id??null}if(fields.Valeur_structure_Code){const row=resolveRow(fields.Valeur_structure_Code,ctx.structures,"Structure_Code");fields.Valeur_structure_Code=row?.id??null}return fields}
function selectionTarget(q,code,ctx){const pool=optionPool(q,ctx),hit=pool.find(o=>String(o.code)===String(code));if(!hit)return null;if(hit.kind==="choice")return{Choix_Code:hit.row.id,ValeurRef_Code:null,Structure_Code:null};if(hit.kind==="reference")return{Choix_Code:null,ValeurRef_Code:hit.row.id,Structure_Code:null};if(hit.kind==="structure")return{Choix_Code:null,ValeurRef_Code:null,Structure_Code:hit.row.id};return null}
async function addElement(response,type,parent,order,statusValue){const ec=unique("SIMELT"),fields={Element_Code:ec,Reponse_Code:response.id,Type_element:type?parent?"Sous-fiche":"Fiche":"Principal",TypeFiche_Code:type?.id??null,Parent_Code:parent?.id??null,Ordre:order,Statut:statusValue,Revision:1,Supprime_logiquement:false,Cle_creation_ACL:String(response.Jeton_acces_ACL||"")};await grist.docApi.applyUserActions([["AddRecord","ELEMENTS_REPONSE",null,fields]]);S.data.ELEMENTS_REPONSE=await fetchRows("ELEMENTS_REPONSE");const el=S.data.ELEMENTS_REPONSE.find(e=>codeOf(e.Element_Code)===ec);if(!el)throw new Error("Élément simulé créé mais non relisible.");return el}
async function writeMatrix(element,q,ctx,rng,index,mode){const kind=matrixKind(q),rows=matrixRows(q,ctx),cols=matrixCols(q,ctx);for(const r of rows){if(["radio","checkbox"].includes(kind)){const vc=unique("SIMVAL");await grist.docApi.applyUserActions([["AddRecord","VALEURS_REPONSE",null,{Valeur_Code:vc,Element_Code:element.id,Question_Code:r.id,Valeur_texte:null}]]);S.data.VALEURS_REPONSE=await fetchRows("VALEURS_REPONSE");const vr=S.data.VALEURS_REPONSE.find(v=>codeOf(v.Valeur_Code)===vc);if(!vr)continue;const selected=kind==="radio"?[cols[intBetween(rng,0,Math.max(0,cols.length-1))]].filter(Boolean):(()=>{const n=Math.min(cols.length,Math.max(1,intBetween(rng,1,Math.min(3,cols.length||1)))),copy=[...cols],out=[];while(copy.length&&out.length<n)out.push(copy.splice(Math.floor(rng()*copy.length),1)[0]);return out})();if(kind==="radio"&&selected[0])await grist.docApi.applyUserActions([["UpdateRecord","VALEURS_REPONSE",vr.id,{Valeur_texte:codeOf(selected[0].Choix_Code)}]]);for(const c of selected)await grist.docApi.applyUserActions([["AddRecord","SELECTIONS_REPONSE",null,{Selection_Code:unique("SIMSEL"),Valeur_Code:vr.id,Choix_Code:c.id,ValeurRef_Code:null,Structure_Code:null}]]);
      }else for(const c of cols){const value=kind==="number"?fakeSimpleValue({...q,Type_question:"Numérique",Valeur_min:c.Minimum,Valeur_max:c.Maximum,Nb_decimales:c.Decimales},ctx,rng,index,mode):`Texte fictif ${index}`;await grist.docApi.applyUserActions([["AddRecord","VALEURS_REPONSE",null,{Valeur_Code:unique("SIMVAL"),Element_Code:element.id,Question_Code:r.id,ColonneMatrice_Code:c.id,Valeur_texte:kind==="text"?String(value):null,Valeur_nombre:kind==="number"?Number(value):null}]]);}}
}
async function writeAnswers(element,questions,ctx,rng,index,mode){const answers=generateAnswers(questions,ctx,rng,index,mode);for(const q of questions){if(q.Active===false||isTrue(q.Est_ligne_matrice))continue;if(!conditionVisible(q,ctx,answers))continue;const qc=codeOf(q.Question_Code),kind=matrixKind(q);if(kind){if($("#with-matrices").checked)await writeMatrix(element,q,ctx,rng,index,mode);continue}const value=answers[qc];if(value===undefined||value===""||value==null)continue;if(isMultiQuestion(q)){const vc=unique("SIMVAL");await grist.docApi.applyUserActions([["AddRecord","VALEURS_REPONSE",null,{Valeur_Code:vc,Element_Code:element.id,Question_Code:q.id,...gristFields(q,"",ctx)}]]);S.data.VALEURS_REPONSE=await fetchRows("VALEURS_REPONSE");const vr=S.data.VALEURS_REPONSE.find(v=>codeOf(v.Valeur_Code)===vc);if(!vr)continue;for(const selected of(Array.isArray(value)?value:[])){const target=selectionTarget(q,selected,ctx);if(target)await grist.docApi.applyUserActions([["AddRecord","SELECTIONS_REPONSE",null,{Selection_Code:unique("SIMSEL"),Valeur_Code:vr.id,...target}]])}}else await grist.docApi.applyUserActions([["AddRecord","VALEURS_REPONSE",null,{Valeur_Code:unique("SIMVAL"),Element_Code:element.id,Question_Code:q.id,...gristFields(q,value,ctx)}]])}}
async function createFicheTree(response,parent,type,ctx,rng,index,mode,statusValue,stats,depth=0){if(depth>5)return;const range=safeCountRange(type,mode==="charge"?5:3),count=intBetween(rng,range.min,Math.max(range.min,range.max));for(let i=0;i<count;i++){const el=await addElement(response,type,parent,i+1,statusValue);if(parent)stats.subFiches++;else stats.fiches++;await writeAnswers(el,qForType(ctx,type),ctx,rng,index+i,mode);if($("#with-subfiches").checked)for(const child of childTypes(type,ctx.ficheTypes))await createFicheTree(response,el,child,ctx,rng,index+i,mode,statusValue,stats,depth+1)}}
async function generate(){const c=selectedCampaign();if(!c){status("Sélectionnez une campagne.",true);return}const count=Math.max(1,Math.min(500,Number($("#count").value)||0));if(count>150&&!confirm(`Vous allez générer ${count} réponses fictives. Cette opération peut créer beaucoup de lignes dans Grist. Continuer ?`))return;const rr=realResponses(c);if(rr.length&&!confirm(`Cette campagne contient déjà ${rr.length} vraie(s) réponse(s).\n\nLes simulations seront ajoutées avec Est_test = True et pourront être supprimées séparément. Continuer ?`))return;const btn=$("#generate");btn.disabled=true;status("Génération en cours…");const mode=$("#mode").value,statusValue=$("#response-status").value,seed=Number($("#seed").value)||hashSeed(c.Campagne_Code),rng=mulberry32(seed),ctx=versionContext(c),campaignRows=groupRows(c),stats={responses:0,fiches:0,subFiches:0,errors:[]};try{for(let i=0;i<count;i++){try{const campaign=campaignRows[i%campaignRows.length]||c,rc=unique("SIMREP"),now=Date.now()/1000,resume=generateResumeToken(),fields={Reponse_Code:rc,Campagne_Code:campaign.id,Version_Code:ctx.version.id,Statut:statusValue,Est_test:true,Revision:1,Supprime_logiquement:false,Jeton_reprise:resume,Jeton_acces_ACL:String(campaign.Jeton_acces||""),Date_creation:now,Date_modification:now,Date_validation:statusValue==="Validé"?now:null,Valide_le:statusValue==="Validé"?now:null};await grist.docApi.applyUserActions([["AddRecord","REPONSES",null,fields]]);S.data.REPONSES=await fetchRows("REPONSES");const response=S.data.REPONSES.find(r=>codeOf(r.Reponse_Code)===rc);if(!response)throw new Error("Réponse simulée créée mais non relisible.");stats.responses++;const principal=await addElement(response,null,null,0,statusValue);await writeAnswers(principal,principalQuestions(ctx),ctx,rng,i+1,mode);if($("#with-fiches").checked)for(const type of rootFicheTypes(ctx.ficheTypes))await createFicheTree(response,null,type,ctx,rng,i+1,mode,statusValue,stats)}catch(e){stats.errors.push(`Réponse ${i+1} : ${e?.message||e}`)}}await load();const lines=[`${stats.responses} réponse(s) fictive(s) créée(s)`,`${stats.fiches} fiche(s)`,`${stats.subFiches} sous-fiche(s)`,`${stats.errors.length} erreur(s)`];log([...lines,...stats.errors]);status(lines.join(" · "),!!stats.errors.length)}catch(e){status(`Génération impossible : ${e?.message||e}`,true);log(e?.stack||e)}finally{btn.disabled=false}}
async function removeSimulations(){const c=selectedCampaign(),responses=testResponses(c);if(!c||!responses.length)return;if(!confirm(`Supprimer définitivement ${responses.length} réponse(s) simulée(s) de cette campagne ?\n\nAucune réponse réelle ne sera supprimée.`))return;const btn=$("#delete");btn.disabled=true;try{const responseIds=new Set(responses.map(r=>String(r.id))),elements=(S.data.ELEMENTS_REPONSE||[]).filter(e=>responseIds.has(String(codeOf(e.Reponse_Code)))||responseIds.has(String(e.Reponse_Code))),elementIds=new Set(elements.map(e=>String(e.id))),values=(S.data.VALEURS_REPONSE||[]).filter(v=>elementIds.has(String(codeOf(v.Element_Code)))||elementIds.has(String(v.Element_Code))),valueIds=new Set(values.map(v=>String(v.id))),selections=(S.data.SELECTIONS_REPONSE||[]).filter(s=>valueIds.has(String(codeOf(s.Valeur_Code)))||valueIds.has(String(s.Valeur_Code)));const actions=[];for(const s of selections)actions.push(["RemoveRecord","SELECTIONS_REPONSE",s.id]);for(const v of values)actions.push(["RemoveRecord","VALEURS_REPONSE",v.id]);for(const e of elements)actions.push(["RemoveRecord","ELEMENTS_REPONSE",e.id]);for(const r of responses)actions.push(["RemoveRecord","REPONSES",r.id]);const batch=150;for(let i=0;i<actions.length;i+=batch)await grist.docApi.applyUserActions(actions.slice(i,i+batch));await load();log([`${responses.length} réponse(s) simulée(s) supprimée(s).`,`${elements.length} élément(s) supprimé(s).`,`${values.length} valeur(s) supprimée(s).`,`${selections.length} sélection(s) supprimée(s).`]);status("Les données de simulation de cette campagne ont été supprimées.")}catch(e){status(`Suppression impossible : ${e?.message||e}`,true);log(e?.stack||e)}finally{btn.disabled=false}}
$("#refresh").onclick=load;$("#generate").onclick=generate;$("#delete").onclick=removeSimulations;grist.ready({requiredAccess:"full"});load();
