import {rowsFromTable,sortByOrder,codeOf} from "../shared/grist-common.js";
const TABLES=["QUESTIONNAIRES","VERSIONS_QUESTIONNAIRES","PAGES","SECTIONS","QUESTIONS","TYPES_FICHES","CHOIX_QUESTIONS","REFERENTIELS"];
const S={data:{},questionnaire:null,version:null,selected:null};
const $=s=>document.querySelector(s);
const esc=(v="")=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const active=r=>r.Active===undefined||r.Active===null||r.Active===""||r.Active===true||r.Active===1||String(r.Active).toLowerCase()==="true";
const first=(r,n,f="")=>{for(const k of n)if(r?.[k]!=null&&r[k]!=="")return r[k];return f};
const field=(r,n)=>n.find(k=>Object.prototype.hasOwnProperty.call(r||{},k))||null;
function ref(v,rows,col){const x=codeOf(v);if(!x)return "";const r=(rows||[]).find(a=>String(a.id)===String(x));return r?codeOf(r[col]):x}
function label(r,t){if(t==="page")return first(r,["Titre","Nom","Libelle","Page_Code"],codeOf(r.Page_Code));if(t==="section")return first(r,["Titre","Nom","Libelle","Section_Code"],codeOf(r.Section_Code));if(t==="fiche")return first(r,["Libelle_singulier","Libelle","Nom","TypeFiche_Code"],codeOf(r.TypeFiche_Code));if(t==="question")return first(r,["Libelle","Libellé","Question","Titre","Question_Code"],codeOf(r.Question_Code));if(t==="questionnaire")return first(r,["Nom","Titre","Questionnaire_Code"],codeOf(r.Questionnaire_Code));return first(r,["Nom","Libelle","Titre","Version_Code"],codeOf(r.Version_Code))}
async function reload(){for(const t of TABLES)S.data[t]=rowsFromTable(await grist.docApi.fetchTable(t));renderSelectors()}
const qForV=v=>ref(v.Questionnaire_Code,S.data.QUESTIONNAIRES,"Questionnaire_Code");
const versions=()=>S.data.VERSIONS_QUESTIONNAIRES.filter(v=>!S.questionnaire||qForV(v)===S.questionnaire);
function renderSelectors(){const qs=S.data.QUESTIONNAIRES;if(!S.questionnaire)S.questionnaire=codeOf(qs[0]?.Questionnaire_Code);$("#questionnaire-select").innerHTML=qs.map(q=>`<option value="${esc(codeOf(q.Questionnaire_Code))}" ${codeOf(q.Questionnaire_Code)===S.questionnaire?"selected":""}>${esc(label(q,"questionnaire"))}</option>`).join("");const vs=versions();if(!vs.some(v=>codeOf(v.Version_Code)===S.version))S.version=codeOf(vs[0]?.Version_Code);$("#version-select").innerHTML=vs.map(v=>`<option value="${esc(codeOf(v.Version_Code))}" ${codeOf(v.Version_Code)===S.version?"selected":""}>${esc(label(v,"version"))}</option>`).join("");renderTree()}
const vm=r=>!("Version_Code" in r)||ref(r.Version_Code,S.data.VERSIONS_QUESTIONNAIRES,"Version_Code")===S.version;
function current(){return {pages:sortByOrder(S.data.PAGES.filter(r=>active(r)&&vm(r))),sections:sortByOrder(S.data.SECTIONS.filter(r=>active(r)&&vm(r))),questions:sortByOrder(S.data.QUESTIONS.filter(r=>active(r)&&vm(r))),fiches:sortByOrder(S.data.TYPES_FICHES.filter(r=>active(r)&&vm(r)))}}
function item(t,r,txt,cls){const on=S.selected?.type===t&&String(S.selected.row.id)===String(r.id);return `<button class="tree-item ${cls} ${on?"selected":""}" data-type="${t}" data-id="${r.id}">${esc(txt)}${t==="fiche"?'<span class="badge">Fiche</span>':""}</button>`}
function renderTree(){const {pages,sections,questions,fiches}=current();let h="";for(const p of pages){const pc=codeOf(p.Page_Code);h+=item("page",p,label(p,"page"),"tree-page");for(const s of sections.filter(x=>ref(x.Page_Code,S.data.PAGES,"Page_Code")===pc)){const sc=codeOf(s.Section_Code);h+=item("section",s,label(s,"section"),"tree-section");const sq=questions.filter(q=>ref(q.Section_Code,S.data.SECTIONS,"Section_Code")===sc);for(const q of sq.filter(q=>!ref(q.TypeFiche_Code,fiches,"TypeFiche_Code")))h+=item("question",q,label(q,"question"),"tree-question");const ft=new Set(sq.map(q=>ref(q.TypeFiche_Code,fiches,"TypeFiche_Code")).filter(Boolean));for(const f of fiches.filter(f=>ft.has(codeOf(f.TypeFiche_Code))))h+=item("fiche",f,label(f,"fiche"),"tree-fiche")}}$("#tree").innerHTML=h||'<div class="empty-state">Aucune page.</div>';document.querySelectorAll(".tree-item").forEach(b=>b.onclick=()=>select(b.dataset.type,b.dataset.id))}
const rows=t=>({page:S.data.PAGES,section:S.data.SECTIONS,question:S.data.QUESTIONS,fiche:S.data.TYPES_FICHES}[t]||[]);
function select(t,id){const r=rows(t).find(x=>String(x.id)===String(id));if(!r)return;S.selected={type:t,row:r};renderTree();renderEditor()}
function input(name,title,value,type="text"){return `<div class="form-field"><label>${esc(title)}<${type==="textarea"?"textarea":"input"} name="${name}" ${type!=="textarea"?`type="${type}"`:""}>${type==="textarea"?esc(value):""}${type==="textarea"?"</textarea>":""}${type!=="textarea"?` value="${esc(value??"")}">`:""}</label></div>`}
function selectHtml(name,title,value,opts){return `<div class="form-field"><label>${esc(title)}<select name="${name}">${opts.map(([v,l])=>`<option value="${esc(v)}"${String(value)===String(v)?" selected":""}>${esc(l)}</option>`).join("")}</select></label></div>`}
const TYPES=[["Texte","Texte court"],["Texte long","Texte long"],["Nombre","Nombre"],["Montant","Montant"],["Date","Date"],["Email","Adresse e-mail"],["Radio","Choix unique (boutons radio)"],["Liste déroulante","Liste déroulante"]];
function choicesFor(q){const qc=codeOf(q.Question_Code);return sortByOrder(S.data.CHOIX_QUESTIONS.filter(c=>ref(c.Question_Code,S.data.QUESTIONS,"Question_Code")===qc&&active(c)))}
function renderEditor(){const {type,row}=S.selected;$("#canvas").innerHTML=`<div class="preview-card"><span class="badge">${esc(type)}</span><h2>${esc(label(row,type))}</h2><p>${type==="question"?"Configurez la question et ses règles simples.":"Modifiez les propriétés puis enregistrez."}</p></div>`;if(type==="fiche"){$("#properties").innerHTML='<div class="empty-state">L’édition des fiches sera activée à l’étape suivante.</div>';return}
 const titleKey=field(row,type==="question"?["Libelle","Libellé","Question","Titre"]:["Titre","Nom","Libelle"]),descKey=field(row,type==="question"?["Aide","Description","Texte_aide"]:["Description","Introduction","Texte"]),orderKey=field(row,["Ordre"]),activeKey=field(row,["Active"]);
 let h='<form id="edit-form" class="form-grid">';if(titleKey)h+=input("title","Libellé / titre",row[titleKey]??"");if(descKey)h+=input("description",type==="question"?"Aide / description":"Description",row[descKey]??"","textarea");
 if(type==="question")h+=questionFields(row);if(orderKey)h+=input("order","Ordre",row[orderKey]??0,"number");if(activeKey)h+=`<label class="check"><input name="active" type="checkbox" ${active(row)?"checked":""}> Actif</label>`;
 h+='<div class="form-actions"><button class="btn btn-primary" type="submit">Enregistrer</button></div></form>';$("#properties").innerHTML=h;bindEditor(type,row,{titleKey,descKey,orderKey,activeKey})}
function questionFields(r){const typeKey=field(r,["Type_question","Type_reponse","Type","Format"]),req=field(r,["Mode_obligation"]),ro=field(r,["Lecture_seule"]),hidden=field(r,["Masquee"]),min=field(r,["Valeur_min"]),max=field(r,["Valeur_max"]),lmin=field(r,["Longueur_min"]),lmax=field(r,["Longueur_max"]),dec=field(r,["Nb_decimales"]),def=field(r,["Valeur_par_defaut"]),refKey=field(r,["Referentiel_Code"]);let h='<div class="editor-section"><h3>Réponse</h3>';
 if(typeKey){let opts=[...TYPES];const cur=String(r[typeKey]??"");if(cur&&!opts.some(x=>x[0]===cur))opts.unshift([cur,`${cur} (valeur actuelle)`]);h+=selectHtml("qtype","Type de question",cur,opts)}
 if(req)h+=selectHtml("required","Caractère obligatoire",r[req]??"Facultative",[["Facultative","Facultative"],["Obligatoire","Obligatoire"]]);
 if(refKey){const current=ref(r[refKey],S.data.REFERENTIELS,"Referentiel_Code");h+=selectHtml("referential","Référentiel",current,[["","Aucun"],...S.data.REFERENTIELS.filter(active).map(x=>[codeOf(x.Referentiel_Code),first(x,["Nom","Libelle","Referentiel_Code"],codeOf(x.Referentiel_Code))])])}
 h+='</div><div class="editor-section"><h3>Validation et comportement</h3><div class="two-cols">';
 if(min)h+=input("min","Valeur minimale",r[min]??"","number");if(max)h+=input("max","Valeur maximale",r[max]??"","number");if(lmin)h+=input("lmin","Longueur minimale",r[lmin]??"","number");if(lmax)h+=input("lmax","Longueur maximale",r[lmax]??"","number");if(dec)h+=input("decimals","Décimales",r[dec]??"","number");if(def)h+=input("default","Valeur par défaut",r[def]??"");h+="</div>";
 if(ro)h+=`<label class="check"><input name="readonly" type="checkbox" ${r[ro]?"checked":""}> Lecture seule</label>`;if(hidden)h+=`<label class="check"><input name="hidden" type="checkbox" ${r[hidden]?"checked":""}> Masquée</label>`;h+="</div>";
 const type=String(r[typeKey]??"").toLowerCase(),hasRef=Boolean(ref(r[refKey],S.data.REFERENTIELS,"Referentiel_Code"));if((type.includes("radio")||type.includes("liste"))&&!hasRef){const cs=choicesFor(r);h+='<div class="editor-section"><h3>Choix proposés</h3><div class="choice-list" id="choice-list">'+cs.map(c=>`<div class="choice-row"><input data-choice-id="${c.id}" value="${esc(first(c,["Libelle","Libellé","Valeur"],""))}"><button type="button" data-remove-choice="${c.id}" title="Retirer">×</button></div>`).join("")+'</div><button type="button" class="secondary-btn" id="add-choice">+ Ajouter un choix</button></div>'}return h}
function bindEditor(type,row,k){const form=$("#edit-form");if($("#add-choice"))$("#add-choice").onclick=()=>{$("#choice-list").insertAdjacentHTML("beforeend",'<div class="choice-row"><input data-new-choice value=""><button type="button" data-remove-new title="Retirer">×</button></div>');bindRemove()};bindRemove();form.onsubmit=async e=>{e.preventDefault();const btn=form.querySelector('button[type="submit"]');if(btn)btn.disabled=true;status("Enregistrement…",false,true);try{const f=new FormData(form),ch={};if(k.titleKey)ch[k.titleKey]=f.get("title");if(k.descKey)ch[k.descKey]=f.get("description");if(k.orderKey)ch[k.orderKey]=Number(f.get("order")||0);if(k.activeKey)ch[k.activeKey]=f.get("active")==="on";if(type==="question")fillQuestionChanges(row,f,ch);const choiceActions=type==="question"?collectChoiceActions(row):[];await grist.docApi.applyUserActions([["UpdateRecord",tableFor(type),Number(row.id),ch],...choiceActions]);await reload();const nr=rows(type).find(x=>String(x.id)===String(row.id));if(nr){S.selected={type,row:nr};renderTree();renderEditor()}status("Enregistré.");}catch(err){status(`Erreur : ${err?.message||err}`,true,true);if(btn)btn.disabled=false;}}}
function bindRemove(){document.querySelectorAll("[data-remove-choice]").forEach(b=>b.onclick=()=>b.closest(".choice-row").dataset.deleted="1");document.querySelectorAll("[data-remove-new]").forEach(b=>b.onclick=()=>b.closest(".choice-row").remove())}
function fillQuestionChanges(r,f,ch){const map=[(["Type_question","Type_reponse","Type","Format"],"qtype"),(["Mode_obligation"],"required"),(["Valeur_min"],"min"),(["Valeur_max"],"max"),(["Longueur_min"],"lmin"),(["Longueur_max"],"lmax"),(["Nb_decimales"],"decimals"),(["Valeur_par_defaut"],"default")];for(const [names,n] of map){const k=field(r,names);if(k)ch[k]=f.get(n)===""?null:(["min","max","lmin","lmax","decimals"].includes(n)?Number(f.get(n)):f.get(n))}for(const [names,n] of [[["Lecture_seule"],"readonly"],[["Masquee"],"hidden"]]){const k=field(r,names);if(k)ch[k]=f.get(n)==="on"}const rk=field(r,["Referentiel_Code"]);if(rk){const c=f.get("referential");ch[rk]=c?(S.data.REFERENTIELS.find(x=>codeOf(x.Referentiel_Code)===c)?.id??null):null}}
function collectChoiceActions(q){const existing=choicesFor(q),acts=[];for(const el of document.querySelectorAll("[data-choice-id]")){const id=Number(el.dataset.choiceId),old=existing.find(c=>c.id===id),lk=field(old,["Libelle","Libellé","Valeur"]);if(el.closest(".choice-row").dataset.deleted==="1")acts.push(["RemoveRecord","CHOIX_QUESTIONS",id]);else if(lk&&String(old[lk]??"")!==el.value)acts.push(["UpdateRecord","CHOIX_QUESTIONS",id,{[lk]:el.value}])}const sample=S.data.CHOIX_QUESTIONS[0]||{},lk=field(sample,["Libelle","Libellé","Valeur"])||"Libelle";let order=Math.max(0,...existing.map(x=>Number(x.Ordre)||0));for(const el of document.querySelectorAll("[data-new-choice]"))if(el.value.trim())acts.push(["AddRecord","CHOIX_QUESTIONS",null,{Choix_Code:unique("CHOIX"),Question_Code:q.id,[lk]:el.value.trim(),Ordre:++order,Active:true}]);return acts}
const tableFor=t=>({page:"PAGES",section:"SECTIONS",question:"QUESTIONS"}[t]);
async function update(t,id,ch){try{await grist.docApi.applyUserActions([["UpdateRecord",tableFor(t),Number(id),ch]]);status("Modification enregistrée.");await reload();const nr=rows(t).find(x=>String(x.id)===String(id));if(nr){S.selected={type:t,row:nr};renderTree();renderEditor()}}catch(e){status(e?.message||e,true)}}
const unique=p=>`${p}_${Date.now().toString(36).toUpperCase()}_${Math.random().toString(36).slice(2,6).toUpperCase()}`;
const versionRow=()=>S.data.VERSIONS_QUESTIONNAIRES.find(v=>codeOf(v.Version_Code)===S.version);
const maxOrder=a=>Math.max(0,...a.map(r=>Number(r.Ordre)||0))+1;
async function add(t){try{const {pages,sections,questions}=current(),v=versionRow();if(!v)throw new Error("Version introuvable.");let table,values;if(t==="page"){table="PAGES";const sm=S.data.PAGES[0]||{};values={Page_Code:unique("PAGE"),Version_Code:v.id,Ordre:maxOrder(pages)};const k=field(sm,["Titre","Nom","Libelle"]);if(k)values[k]="Nouvelle page";if(field(sm,["Active"]))values.Active=true}if(t==="section"){const p=S.selected?.type==="page"?S.selected.row:S.selected?.type==="section"?S.data.PAGES.find(x=>String(x.id)===String(S.selected.row.Page_Code)):null;if(!p)throw new Error("Sélectionnez d’abord la page.");table="SECTIONS";const sm=S.data.SECTIONS[0]||{};values={Section_Code:unique("SEC"),Version_Code:v.id,Page_Code:p.id,Ordre:maxOrder(sections.filter(s=>String(s.Page_Code)===String(p.id)))};const k=field(sm,["Titre","Nom","Libelle"]);if(k)values[k]="Nouvelle section";if(field(sm,["Active"]))values.Active=true}if(t==="question"){const s=S.selected?.type==="section"?S.selected.row:S.selected?.type==="question"?S.data.SECTIONS.find(x=>String(x.id)===String(S.selected.row.Section_Code)):null;if(!s)throw new Error("Sélectionnez d’abord la section.");const p=S.data.PAGES.find(x=>String(x.id)===String(s.Page_Code));table="QUESTIONS";const sm=S.data.QUESTIONS[0]||{};values={Question_Code:unique("Q"),Version_Code:v.id,Section_Code:s.id,Ordre:maxOrder(questions.filter(q=>String(q.Section_Code)===String(s.id)))};if(p&&field(sm,["Page_Code"]))values.Page_Code=p.id;const k=field(sm,["Libelle","Libellé","Question","Titre"]);if(k)values[k]="Nouvelle question";if(field(sm,["Active"]))values.Active=true;if(field(sm,["Mode_obligation"]))values.Mode_obligation="Facultative";const tk=field(sm,["Type_question","Type_reponse","Type","Format"]);if(tk)values[tk]="Texte"}await grist.docApi.applyUserActions([["AddRecord",table,null,values]]);status("Élément ajouté.");await reload()}catch(e){status(e?.message||e,true)}}
function status(m,err=false,persistent=false){const node=$("#status");node.innerHTML=`<div class="${err?"status-error":"status-ok"}">${esc(m)}</div>`;if(!err&&!persistent)setTimeout(()=>{if(node.textContent===m)node.innerHTML=""},3500)}
function bind(){$("#questionnaire-select").onchange=e=>{S.questionnaire=e.target.value;S.version=null;S.selected=null;renderSelectors()};$("#version-select").onchange=e=>{S.version=e.target.value;S.selected=null;renderTree()};$("#add-page").onclick=()=>add("page");$("#add-section").onclick=()=>add("section");$("#add-question").onclick=()=>add("question")}
async function start(){try{grist.ready({requiredAccess:"full"});await reload();bind()}catch(e){status(`Impossible de charger le Concepteur : ${e?.message||e}`,true)}}start();
