import {rowsFromTable,sortByOrder,codeOf} from "../shared/grist-common.js";
const TABLES=["QUESTIONNAIRES","VERSIONS_QUESTIONNAIRES","PAGES","SECTIONS","QUESTIONS","TYPES_FICHES","CHOIX_QUESTIONS","REFERENTIELS","VALEURS_REFERENTIELS","STRUCTURES","CONDITIONS","REGLES_CONDITION"];
const S={data:{},questionnaire:null,version:null,selected:null};
const $=s=>document.querySelector(s);
const esc=(v="")=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const active=r=>{const v=Object.prototype.hasOwnProperty.call(r||{},"Actif")?r.Actif:r?.Active;return v===undefined||v===null||v===""||v===true||v===1||String(v).toLowerCase()==="true"};
const first=(r,n,f="")=>{for(const k of n)if(r?.[k]!=null&&r[k]!=="")return r[k];return f};
const field=(r,n)=>n.find(k=>Object.prototype.hasOwnProperty.call(r||{},k))||null;
function ref(v,rows,col){const x=codeOf(v);if(!x)return "";const r=(rows||[]).find(a=>String(a.id)===String(x));return r?codeOf(r[col]):x}
function label(r,t){if(t==="page")return first(r,["Titre","Nom","Libelle","Page_Code"],codeOf(r.Page_Code));if(t==="section")return first(r,["Titre","Nom","Libelle","Section_Code"],codeOf(r.Section_Code));if(t==="fiche")return first(r,["Libelle_singulier","Libelle","Nom","TypeFiche_Code"],codeOf(r.TypeFiche_Code));if(t==="question")return first(r,["Libelle","Libellé","Question","Titre","Question_Code"],codeOf(r.Question_Code));if(t==="questionnaire")return first(r,["Nom","Titre","Questionnaire_Code"],codeOf(r.Questionnaire_Code));return first(r,["Nom","Libelle","Titre","Version_Code"],codeOf(r.Version_Code))}
async function reload(){for(const t of TABLES)S.data[t]=rowsFromTable(await grist.docApi.fetchTable(t));renderSelectors()}
const qForV=v=>ref(v.Questionnaire_Code,S.data.QUESTIONNAIRES,"Questionnaire_Code");
const versions=()=>S.data.VERSIONS_QUESTIONNAIRES.filter(v=>!S.questionnaire||qForV(v)===S.questionnaire);
function renderSelectors(){const qs=S.data.QUESTIONNAIRES;if(!S.questionnaire)S.questionnaire=codeOf(qs[0]?.Questionnaire_Code);$("#questionnaire-select").innerHTML=qs.map(q=>`<option value="${esc(codeOf(q.Questionnaire_Code))}" ${codeOf(q.Questionnaire_Code)===S.questionnaire?"selected":""}>${esc(label(q,"questionnaire"))}</option>`).join("");const vs=versions();if(!vs.some(v=>codeOf(v.Version_Code)===S.version))S.version=codeOf(vs[0]?.Version_Code);$("#version-select").innerHTML=vs.map(v=>`<option value="${esc(codeOf(v.Version_Code))}" ${codeOf(v.Version_Code)===S.version?"selected":""}>${esc(label(v,"version"))}</option>`).join("");renderTree()}
const vm=r=>!("Version_Code" in r)||ref(r.Version_Code,S.data.VERSIONS_QUESTIONNAIRES,"Version_Code")===S.version;
function current(){return {pages:sortByOrder(S.data.PAGES.filter(r=>active(r)&&vm(r))),sections:sortByOrder(S.data.SECTIONS.filter(r=>active(r)&&vm(r))),questions:sortByOrder(S.data.QUESTIONS.filter(r=>active(r)&&vm(r))),fiches:sortByOrder(S.data.TYPES_FICHES.filter(r=>active(r)&&vm(r)))}}
function item(t,r,txt,cls){const on=S.selected?.type===t&&String(S.selected.row.id)===String(r.id);return `<button class="tree-item ${cls} ${on?"selected":""}" data-type="${t}" data-id="${r.id}">${esc(txt)}${t==="fiche"?'<span class="badge">Fiche</span>':""}</button>`}
function renderTree(){const {pages,sections,questions,fiches}=current();let h="";for(const p of pages){const pc=codeOf(p.Page_Code);h+=item("page",p,label(p,"page"),"tree-page");for(const s of sections.filter(x=>ref(x.Page_Code,S.data.PAGES,"Page_Code")===pc)){const sc=codeOf(s.Section_Code);h+=item("section",s,label(s,"section"),"tree-section");const sq=questions.filter(q=>ref(q.Section_Code,S.data.SECTIONS,"Section_Code")===sc);for(const q of sq.filter(q=>!ref(q.TypeFiche_Code,fiches,"TypeFiche_Code")))h+=item("question",q,label(q,"question"),"tree-question");const ft=new Set(sq.map(q=>ref(q.TypeFiche_Code,fiches,"TypeFiche_Code")).filter(Boolean));for(const f of fiches.filter(f=>ft.has(codeOf(f.TypeFiche_Code))))h+=item("fiche",f,label(f,"fiche"),"tree-fiche")}}$("#tree").innerHTML=h||'<div class="empty-state">Aucune page.</div>';document.querySelectorAll(".tree-item").forEach(b=>b.onclick=()=>select(b.dataset.type,b.dataset.id))}
const rows=t=>({page:S.data.PAGES,section:S.data.SECTIONS,question:S.data.QUESTIONS,fiche:S.data.TYPES_FICHES}[t]||[]);
function select(t,id){const r=rows(t).find(x=>String(x.id)===String(id));if(!r)return;S.selected={type:t,row:r};renderTree();renderEditor()}
function input(name,title,value,type="text"){if(type==="textarea")return `<div class="form-field"><label>${esc(title)}<textarea name="${name}">${esc(value??"")}</textarea></label></div>`;return `<div class="form-field"><label>${esc(title)}<input name="${name}" type="${type}" value="${esc(value??"")}"></label></div>`}
function selectHtml(name,title,value,opts){return `<div class="form-field"><label>${esc(title)}<select name="${name}">${opts.map(([v,l])=>`<option value="${esc(v)}"${String(value)===String(v)?" selected":""}>${esc(l)}</option>`).join("")}</select></label></div>`}
const TYPES=[["Texte","Texte court"],["Texte long","Texte long"],["Nombre","Nombre"],["Montant","Montant"],["Date","Date"],["Email","Adresse e-mail"],["Radio","Choix unique (boutons radio)"],["Liste déroulante","Liste déroulante"]];
function choicesFor(q){const qc=codeOf(q.Question_Code);return sortByOrder(S.data.CHOIX_QUESTIONS.filter(c=>ref(c.Question_Code,S.data.QUESTIONS,"Question_Code")===qc&&active(c)))}
function renderEditor(){const {type,row}=S.selected;$("#canvas").innerHTML=`<div class="preview-card"><span class="badge">${esc(type)}</span><h2>${esc(label(row,type))}</h2><p>${type==="question"?"Configurez la question et ses règles simples.":"Modifiez les propriétés puis enregistrez."}</p></div>`;if(type==="fiche"){$("#properties").innerHTML='<div class="empty-state">L’édition des fiches sera activée à l’étape suivante.</div>';return}
 const titleKey=field(row,type==="question"?["Libelle","Libellé","Question","Titre"]:["Titre","Nom","Libelle"]),descKey=field(row,type==="question"?["Aide","Description","Texte_aide"]:["Description","Introduction","Texte"]),orderKey=field(row,["Ordre"]),activeKey=field(row,["Active"]);
 let h='<form id="edit-form" class="form-grid">';if(titleKey)h+=input("title","Libellé / titre",row[titleKey]??"");if(descKey)h+=input("description",type==="question"?"Aide / description":"Description",row[descKey]??"","textarea");
 if(type==="question")h+=questionFields(row);if(orderKey)h+=input("order","Ordre",row[orderKey]??0,"number");if(activeKey)h+=`<label class="check"><input name="active" type="checkbox" ${active(row)?"checked":""}> Actif</label>`;
 h+='<div class="form-actions"><button class="btn btn-primary" type="submit">Enregistrer</button></div></form>';$("#properties").innerHTML=h;bindEditor(type,row,{titleKey,descKey,orderKey,activeKey})}
function questionFields(r){const typeKey=field(r,["Type_question","Type_reponse","Type","Format"]),req=field(r,["Mode_obligation"]),ro=field(r,["Lecture_seule"]),hidden=field(r,["Masquee"]),min=field(r,["Valeur_min"]),max=field(r,["Valeur_max"]),lmin=field(r,["Longueur_min"]),lmax=field(r,["Longueur_max"]),dec=field(r,["Nb_decimales"]),def=field(r,["Valeur_par_defaut"]),refKey=field(r,["Referentiel_Code"]);let h='<div class="editor-section"><h3>Réponse</h3>';
 if(typeKey){let opts=[...TYPES];const cur=String(r[typeKey]??"");if(cur&&!opts.some(x=>x[0]===cur))opts.unshift([cur,`${cur} (valeur actuelle)`]);h+=selectHtml("qtype","Type de question",cur,opts)}
 if(req)h+=selectHtml("required","Caractère obligatoire",r[req]??"Facultative",[["Facultative","Facultative"],["Obligatoire","Obligatoire"]]);
 if(refKey){const current=ref(r[refKey],S.data.REFERENTIELS,"Referentiel_Code");h+=`<div data-kind="choice-ref">${selectHtml("referential","Référentiel",current,[["","Aucun"],...S.data.REFERENTIELS.filter(active).map(x=>[codeOf(x.Referentiel_Code),first(x,["Nom","Libelle","Referentiel_Code"],codeOf(x.Referentiel_Code))])])}</div>`}
 h+='</div><div class="editor-section"><h3>Validation et comportement</h3>';
 if(min||max||dec)h+='<div class="two-cols" data-kind="numeric">'+(min?input("min","Valeur minimale",r[min]??"","number"):"")+(max?input("max","Valeur maximale",r[max]??"","number"):"")+(dec?input("decimals","Décimales",r[dec]??"","number"):"")+"</div>";
 if(lmin||lmax)h+='<div class="two-cols" data-kind="text-length">'+(lmin?input("lmin","Longueur minimale",r[lmin]??"","number"):"")+(lmax?input("lmax","Longueur maximale",r[lmax]??"","number"):"")+"</div>";
 if(def)h+=`<div data-kind="default">${input("default","Valeur par défaut",r[def]??"")}</div>`;
 if(ro)h+=`<label class="check"><input name="readonly" type="checkbox" ${r[ro]?"checked":""}> Lecture seule</label>`;if(hidden)h+=`<label class="check"><input name="hidden" type="checkbox" ${r[hidden]?"checked":""}> Masquée</label>`;h+="</div>";
 h+=conditionFields(r);
 const cs=choicesFor(r);h+='<div class="editor-section" data-kind="direct-choices"><h3>Choix proposés</h3><div class="choice-list" id="choice-list">'+cs.map(c=>`<div class="choice-row"><input data-choice-id="${c.id}" value="${esc(first(c,["Libelle","Libellé","Valeur"],""))}"><button type="button" data-remove-choice="${c.id}" title="Retirer">×</button></div>`).join("")+'</div><div class="choice-actions"><button type="button" class="secondary-btn" id="add-choice">+ Ajouter un choix</button><button type="button" class="secondary-btn" id="paste-choices">Coller une liste</button></div><div id="bulk-choices" class="bulk-choices" style="display:none"><label>Un choix par ligne<textarea id="bulk-choices-text" placeholder="Choix 1&#10;Choix 2&#10;Choix 3"></textarea></label><div class="choice-actions"><button type="button" class="secondary-btn" id="import-choices">Ajouter les choix</button><button type="button" class="secondary-btn" id="cancel-bulk">Annuler</button></div></div></div>';return h}


function conditionByRef(v){const id=codeOf(v);return S.data.CONDITIONS.find(c=>String(c.id)===String(id))||null}
function rulesForCondition(c){if(!c)return[];return sortByOrder(S.data.REGLES_CONDITION.filter(r=>String(codeOf(r.Condition_Code))===String(c.id)))}
function conditionSummary(c){if(!c)return"Aucune";const rules=rulesForCondition(c),logic=String(c.Operateur_global||"AND").toUpperCase();if(!rules.length)return first(c,["Nom","Condition_Code"],"Condition");return rules.map(r=>{const q=S.data.QUESTIONS.find(x=>String(x.id)===String(codeOf(r.Question_source_Code)));return `${label(q||{},"question")} ${r.Operateur||"="} ${r.Valeur_comparaison??""}`}).join(` ${logic==="OR"?"OU":"ET"} `)}
function conditionFields(r){const ak=field(r,["Condition_affichage_Code"]),ok=field(r,["Condition_obligation_Code"]);let h='<div class="editor-section"><h3>Conditions</h3><p class="field-help">Affichage et obligation utilisent le moteur générique de conditions.</p>';if(ak){const c=conditionByRef(r[ak]);h+=`<div class="condition-card"><strong>Afficher cette question si…</strong><div>${esc(conditionSummary(c))}</div><button type="button" class="secondary-btn" data-edit-condition="display">${c?"Modifier":"Ajouter une condition"}</button></div>`}if(ok){const c=conditionByRef(r[ok]);h+=`<div class="condition-card"><strong>Rendre obligatoire si…</strong><div>${esc(conditionSummary(c))}</div><button type="button" class="secondary-btn" data-edit-condition="required">${c?"Modifier":"Ajouter une condition"}</button></div>`}return h+"</div>"}
function eligibleSourceQuestions(target){const all=current().questions;return all.filter(q=>String(q.id)!==String(target.id))}
function conditionSourceById(id){return S.data.QUESTIONS.find(q=>String(q.id)===String(id))||null}
function conditionOperators(q){const t=String(first(q,["Type_question","Type_reponse","Type","Format"],"")).toLowerCase();if(t.includes("nombre")||t.includes("montant")||t.includes("date"))return [["=","Est égal à"],["!=","Est différent de"],[">","Supérieur à"],[">=","Supérieur ou égal à"],["<","Inférieur à"],["<=","Inférieur ou égal à"],["vide","Est vide"],["non vide","N’est pas vide"]];if(t.includes("radio")||t.includes("liste")||t.includes("déroul"))return [["=","Est égal à"],["!=","Est différent de"],["vide","Est vide"],["non vide","N’est pas vide"]];return [["=","Est égal à"],["!=","Est différent de"],["contient","Contient"],["vide","Est vide"],["non vide","N’est pas vide"]]}
function referentialForQuestion(q){const id=codeOf(q?.Referentiel_Code);return S.data.REFERENTIELS.find(r=>String(r.id)===String(id))||null}
function conditionModalities(q){const direct=choicesFor(q).map(c=>[String(c.Valeur??c.Libelle??""),String(c.Libelle??c.Valeur??"")]).filter(x=>x[0]||x[1]);if(direct.length)return direct;const refRow=referentialForQuestion(q);if(!refRow)return[];const refCode=codeOf(refRow.Referentiel_Code),source=String(refRow.Type_source??"").toUpperCase();if(source==="STRUCTURES"){return sortByOrder((S.data.STRUCTURES||[]).filter(active)).map(s=>[String(s.Structure_Code??""),String(first(s,["Nom","Libelle","Structure_Code"],s.Structure_Code??""))]).filter(x=>x[0])}return sortByOrder((S.data.VALEURS_REFERENTIELS||[]).filter(v=>ref(v.Referentiel_Code,S.data.REFERENTIELS,"Referentiel_Code")===refCode&&active(v))).map(v=>[String(v.Valeur_Code??v.Code??v.Valeur??v.Libelle??""),String(first(v,["Libelle","Nom","Valeur","Valeur_Code","Code"],""))]).filter(x=>x[0]||x[1])}
function conditionValueControl(q,value=""){const t=String(first(q,["Type_question","Type_reponse","Type","Format"],"")).toLowerCase(),mods=q?conditionModalities(q):[];if((t.includes("radio")||t.includes("liste")||t.includes("déroul"))&&mods.length)return selectHtml("cond-value","Modalité",value,[["","Sélectionner une modalité…"],...mods]);if(t.includes("nombre")||t.includes("montant"))return input("cond-value","Valeur attendue",value,"number");if(t.includes("date"))return input("cond-value","Valeur attendue",value,"date");return input("cond-value","Valeur attendue",value)}
function refreshConditionBuilder(existingOp="",existingValue=""){const box=$("#condition-builder");if(!box)return;const source=conditionSourceById(box.querySelector('[name="cond-source"]')?.value),opWrap=$("#cond-op-wrap"),valWrap=$("#cond-value-wrap");if(!source){opWrap.innerHTML="";valWrap.innerHTML="";return}const ops=conditionOperators(source),op=ops.some(x=>x[0]===existingOp)?existingOp:ops[0][0];opWrap.innerHTML=selectHtml("cond-op","Opérateur",op,ops);valWrap.innerHTML=conditionValueControl(source,existingValue);const opEl=box.querySelector('[name="cond-op"]');if(opEl)opEl.onchange=()=>{valWrap.style.display=["vide","non vide"].includes(opEl.value)?"none":""};if(opEl)opEl.onchange()}
function conditionEditorHtml(kind,target){const refKey=kind==="display"?field(target,["Condition_affichage_Code"]):field(target,["Condition_obligation_Code"]),cond=refKey?conditionByRef(target[refKey]):null,rules=rulesForCondition(cond),rule=rules[0]||{},sourceId=codeOf(rule.Question_source_Code),sources=eligibleSourceQuestions(target);return `<div class="condition-builder" id="condition-builder"><h3>${kind==="display"?"Afficher cette question si…":"Rendre obligatoire si…"}</h3>${selectHtml("cond-source","Question source",sourceId,[["","Sélectionner…"],...sources.map(q=>[q.id,label(q,"question")])])}<div id="cond-op-wrap"></div><div id="cond-value-wrap"></div><div class="form-actions"><button type="button" class="btn btn-primary" id="save-condition">Enregistrer la condition</button>${cond?'<button type="button" class="secondary-btn" id="remove-condition">Retirer la condition</button>':""}<button type="button" class="secondary-btn" id="cancel-condition">Annuler</button></div><p class="field-help">Pour une question Radio ou Liste déroulante, sélectionnez directement la modalité, qu’elle provienne de choix directs ou d’un référentiel.</p><input type="hidden" id="cond-existing-op" value="${esc(rule.Operateur||"=")}"><input type="hidden" id="cond-existing-value" value="${esc(rule.Valeur_comparaison??"")}"></div>`}
function bindConditionBuilder(kind,row){const box=$("#condition-builder"),src=box?.querySelector('[name="cond-source"]');if(!box||!src)return;refreshConditionBuilder($("#cond-existing-op")?.value||"=",$("#cond-existing-value")?.value||"");src.onchange=()=>refreshConditionBuilder("","");$("#save-condition").onclick=async()=>{try{await saveSimpleCondition(kind,row)}catch(e){status(`Erreur : ${e?.message||e}`,true,true)}};$("#cancel-condition").onclick=()=>$("#condition-builder")?.remove();if($("#remove-condition"))$("#remove-condition").onclick=async()=>{try{await removeSimpleCondition(kind,row)}catch(e){status(`Erreur : ${e?.message||e}`,true,true)}}}
async function saveSimpleCondition(kind,target){const box=$("#condition-builder"),source=box.querySelector('[name="cond-source"]')?.value,op=box.querySelector('[name="cond-op"]')?.value||"=",val=box.querySelector('[name="cond-value"]')?.value??"";if(!source)throw new Error("Sélectionnez une question source.");const refKey=kind==="display"?field(target,["Condition_affichage_Code"]):field(target,["Condition_obligation_Code"]);if(!refKey)throw new Error("Colonne de condition absente sur QUESTIONS.");let cond=conditionByRef(target[refKey]),acts=[];if(!cond){const code=unique("COND");acts.push(["AddRecord","CONDITIONS",null,{Condition_Code:code,Version_Code:versionRow().id,Nom:kind==="display"?`Affichage — ${label(target,"question")}`:`Obligation — ${label(target,"question")}`,Operateur_global:"AND",Active:true}]);await grist.docApi.applyUserActions(acts);await reload();cond=S.data.CONDITIONS.find(c=>codeOf(c.Condition_Code)===code);if(!cond)throw new Error("Condition créée mais introuvable après relecture.");await grist.docApi.applyUserActions([["UpdateRecord","QUESTIONS",Number(target.id),{[refKey]:cond.id}]])}const old=rulesForCondition(cond);const ruleValues={Regle_Code:unique("RCOND"),Condition_Code:cond.id,Ordre:1,Source:"Question",Question_source_Code:Number(source),Operateur:op,Valeur_comparaison:val};if(old[0])await grist.docApi.applyUserActions([["UpdateRecord","REGLES_CONDITION",Number(old[0].id),{Ordre:1,Source:"Question",Question_source_Code:Number(source),Operateur:op,Valeur_comparaison:val}]]);else await grist.docApi.applyUserActions([["AddRecord","REGLES_CONDITION",null,ruleValues]]);await reload();const fresh=S.data.QUESTIONS.find(q=>String(q.id)===String(target.id));if(fresh){S.selected={type:"question",row:fresh};renderTree();renderEditor()}status("Condition enregistrée.")}
async function removeSimpleCondition(kind,target){const refKey=kind==="display"?field(target,["Condition_affichage_Code"]):field(target,["Condition_obligation_Code"]);if(!refKey)return;await grist.docApi.applyUserActions([["UpdateRecord","QUESTIONS",Number(target.id),{[refKey]:null}]]);await reload();const fresh=S.data.QUESTIONS.find(q=>String(q.id)===String(target.id));if(fresh){S.selected={type:"question",row:fresh};renderTree();renderEditor()}status("Condition retirée.")}
function refreshQuestionFields(){const form=$("#edit-form");if(!form)return;const t=String(form.elements.qtype?.value??"").toLowerCase(),isNum=t.includes("nombre")||t.includes("montant"),isText=t==="texte"||t.includes("texte long")||t.includes("email"),isChoice=t.includes("radio")||t.includes("liste")||t.includes("déroul"),refWrap=form.querySelector('[data-kind="choice-ref"]'),direct=form.querySelector('[data-kind="direct-choices"]'),numeric=form.querySelector('[data-kind="numeric"]'),textLen=form.querySelector('[data-kind="text-length"]');if(numeric)numeric.style.display=isNum?"":"none";if(textLen)textLen.style.display=isText?"":"none";if(refWrap)refWrap.style.display=isChoice?"":"none";const hasRef=Boolean(form.elements.referential?.value);if(direct)direct.style.display=isChoice&&!hasRef?"":"none"}
function appendChoiceRows(values){const list=$("#choice-list");if(!list)return;for(const value of values)list.insertAdjacentHTML("beforeend",`<div class="choice-row"><input data-new-choice value="${esc(value)}"><button type="button" data-remove-new title="Retirer">×</button></div>`)}
function bindEditor(type,row,k){const form=$("#edit-form");if(type==="question"){if(form.elements.qtype)form.elements.qtype.onchange=refreshQuestionFields;if(form.elements.referential)form.elements.referential.onchange=refreshQuestionFields;refreshQuestionFields()}if($("#add-choice"))$("#add-choice").onclick=()=>{appendChoiceRows([""]);bindRemove()};if($("#paste-choices"))$("#paste-choices").onclick=()=>{$("#bulk-choices").style.display="block";$("#bulk-choices-text").focus()};if($("#cancel-bulk"))$("#cancel-bulk").onclick=()=>{$("#bulk-choices").style.display="none";$("#bulk-choices-text").value=""};if($("#import-choices"))$("#import-choices").onclick=()=>{const vals=$("#bulk-choices-text").value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);appendChoiceRows(vals);$("#bulk-choices-text").value="";$("#bulk-choices").style.display="none";bindRemove()};document.querySelectorAll("[data-edit-condition]").forEach(b=>b.onclick=()=>{const kind=b.dataset.editCondition;$("#condition-builder")?.remove();$("#canvas").insertAdjacentHTML("beforeend",conditionEditorHtml(kind,row));bindConditionBuilder(kind,row)});bindRemove();form.onsubmit=async e=>{e.preventDefault();const btn=form.querySelector('button[type="submit"]');if(btn)btn.disabled=true;status("Enregistrement…",false,true);try{const f=new FormData(form),ch={};if(k.titleKey)ch[k.titleKey]=f.get("title");if(k.descKey)ch[k.descKey]=f.get("description");if(k.orderKey)ch[k.orderKey]=Number(f.get("order")||0);if(k.activeKey)ch[k.activeKey]=f.get("active")==="on";if(type==="question")fillQuestionChanges(row,f,ch);const choiceActions=type==="question"?collectChoiceActions(row):[];await grist.docApi.applyUserActions([["UpdateRecord",tableFor(type),Number(row.id),ch],...choiceActions]);const stableCode=type==="question"?codeOf(row.Question_Code):type==="page"?codeOf(row.Page_Code):type==="section"?codeOf(row.Section_Code):"";await reload();const nr=rows(type).find(x=>stableCode&&codeOf(x[type==="question"?"Question_Code":type==="page"?"Page_Code":"Section_Code"])===stableCode)||rows(type).find(x=>String(x.id)===String(row.id));if(nr){S.selected={type,row:nr};renderTree();renderEditor()}status("Enregistré.");}catch(err){status(`Erreur : ${err?.message||err}`,true,true);if(btn)btn.disabled=false;}}}
function bindRemove(){document.querySelectorAll("[data-remove-choice]").forEach(b=>b.onclick=()=>{const row=b.closest(".choice-row");row.dataset.deleted=row.dataset.deleted==="1"?"0":"1";row.classList.toggle("choice-deleted",row.dataset.deleted==="1");b.textContent=row.dataset.deleted==="1"?"↶":"×";b.title=row.dataset.deleted==="1"?"Annuler la suppression":"Supprimer"});document.querySelectorAll("[data-remove-new]").forEach(b=>b.onclick=()=>b.closest(".choice-row").remove())}
function fillQuestionChanges(r,f,ch){const map=[[["Type_question","Type_reponse","Type","Format"],"qtype"],[["Mode_obligation"],"required"],[["Valeur_min"],"min"],[["Valeur_max"],"max"],[["Longueur_min"],"lmin"],[["Longueur_max"],"lmax"],[["Nb_decimales"],"decimals"],[["Valeur_par_defaut"],"default"]];for(const [names,n] of map){const k=field(r,names);if(k)ch[k]=f.get(n)===""?null:(["min","max","lmin","lmax","decimals"].includes(n)?Number(f.get(n)):f.get(n))}for(const [names,n] of [[["Lecture_seule"],"readonly"],[["Masquee"],"hidden"]]){const k=field(r,names);if(k)ch[k]=f.get(n)==="on"}const rk=field(r,["Referentiel_Code"]);if(rk){const c=f.get("referential");ch[rk]=c?(S.data.REFERENTIELS.find(x=>codeOf(x.Referentiel_Code)===c)?.id??null):null}}
function collectChoiceActions(q){const existing=choicesFor(q),acts=[];for(const el of document.querySelectorAll("[data-choice-id]")){const id=Number(el.dataset.choiceId),old=existing.find(c=>c.id===id),lk=field(old,["Libelle","Libellé","Valeur"]);if(el.closest(".choice-row").dataset.deleted==="1")acts.push(["RemoveRecord","CHOIX_QUESTIONS",id]);else if(lk&&String(old[lk]??"")!==el.value)acts.push(["UpdateRecord","CHOIX_QUESTIONS",id,{[lk]:el.value}])}const lk="Libelle";let order=Math.max(0,...existing.map(x=>Number(x.Ordre)||0));for(const el of document.querySelectorAll("[data-new-choice]"))if(el.value.trim()){acts.push(["AddRecord","CHOIX_QUESTIONS",null,{Choix_Code:unique("CHOIX"),Question_Code:q.id,Libelle:el.value.trim(),Valeur:el.value.trim(),Ordre:++order,Exclusif:false,Fixe_si_melange:false,Actif:true}])}return acts}
const tableFor=t=>({page:"PAGES",section:"SECTIONS",question:"QUESTIONS"}[t]);
async function update(t,id,ch){try{await grist.docApi.applyUserActions([["UpdateRecord",tableFor(t),Number(id),ch]]);status("Modification enregistrée.");await reload();const nr=rows(t).find(x=>String(x.id)===String(id));if(nr){S.selected={type:t,row:nr};renderTree();renderEditor()}}catch(e){status(e?.message||e,true)}}
const unique=p=>`${p}_${Date.now().toString(36).toUpperCase()}_${Math.random().toString(36).slice(2,6).toUpperCase()}`;
const versionRow=()=>S.data.VERSIONS_QUESTIONNAIRES.find(v=>codeOf(v.Version_Code)===S.version);
const maxOrder=a=>Math.max(0,...a.map(r=>Number(r.Ordre)||0))+1;
async function add(t){try{const {pages,sections,questions}=current(),v=versionRow();if(!v)throw new Error("Version introuvable.");let table,values;if(t==="page"){table="PAGES";const sm=S.data.PAGES[0]||{};values={Page_Code:unique("PAGE"),Version_Code:v.id,Ordre:maxOrder(pages)};const k=field(sm,["Titre","Nom","Libelle"]);if(k)values[k]="Nouvelle page";if(field(sm,["Active"]))values.Active=true}if(t==="section"){const p=S.selected?.type==="page"?S.selected.row:S.selected?.type==="section"?S.data.PAGES.find(x=>String(x.id)===String(S.selected.row.Page_Code)):null;if(!p)throw new Error("Sélectionnez d’abord la page.");table="SECTIONS";const sm=S.data.SECTIONS[0]||{};values={Section_Code:unique("SEC"),Version_Code:v.id,Page_Code:p.id,Ordre:maxOrder(sections.filter(s=>String(s.Page_Code)===String(p.id)))};const k=field(sm,["Titre","Nom","Libelle"]);if(k)values[k]="Nouvelle section";if(field(sm,["Active"]))values.Active=true}if(t==="question"){const s=S.selected?.type==="section"?S.selected.row:S.selected?.type==="question"?S.data.SECTIONS.find(x=>String(x.id)===String(S.selected.row.Section_Code)):null;if(!s)throw new Error("Sélectionnez d’abord la section.");const p=S.data.PAGES.find(x=>String(x.id)===String(s.Page_Code));table="QUESTIONS";const sm=S.data.QUESTIONS[0]||{};values={Question_Code:unique("Q"),Version_Code:v.id,Section_Code:s.id,Ordre:maxOrder(questions.filter(q=>String(q.Section_Code)===String(s.id)))};if(p&&field(sm,["Page_Code"]))values.Page_Code=p.id;const k=field(sm,["Libelle","Libellé","Question","Titre"]);if(k)values[k]="Nouvelle question";if(field(sm,["Active"]))values.Active=true;if(field(sm,["Mode_obligation"]))values.Mode_obligation="Facultative";const tk=field(sm,["Type_question","Type_reponse","Type","Format"]);if(tk)values[tk]="Texte"}await grist.docApi.applyUserActions([["AddRecord",table,null,values]]);status("Élément ajouté.");await reload()}catch(e){status(e?.message||e,true)}}
function status(m,err=false,persistent=false){const node=$("#status");node.innerHTML=`<div class="${err?"status-error":"status-ok"}">${esc(m)}</div>`;if(!err&&!persistent)setTimeout(()=>{if(node.textContent===m)node.innerHTML=""},3500)}
function bind(){$("#questionnaire-select").onchange=e=>{S.questionnaire=e.target.value;S.version=null;S.selected=null;renderSelectors()};$("#version-select").onchange=e=>{S.version=e.target.value;S.selected=null;renderTree()};$("#add-page").onclick=()=>add("page");$("#add-section").onclick=()=>add("section");$("#add-question").onclick=()=>add("question")}
async function start(){try{grist.ready({requiredAccess:"full"});await reload();bind()}catch(e){status(`Impossible de charger le Concepteur : ${e?.message||e}`,true)}}start();
